### ISSUE TITLE
nheko crashes!

### ISSUE THREAD

**Issue by DaKnig** [Nheko-Reborn/nheko#1081]
### Describe the bug

nheko crashes with a coredump when trying editing a message while offline

### To Reproduce

3. turn off wifi
1. write a message in a chatroom
4. write another message in the same chatroom
1. edit the message from step 4. , then send
5. nheko crashes, coredump emitted
9. profit (?) 

### What happened?

nheko crashes after a few seconds

### Expected behavior

nheko doesn't crash

### Screenshots

black.png

### Version

0.9.3 and flatpak nightly

### Operating system

Linux

### Installation method

Flatpak nightly repo or download

### Desktop Environment

i3

### Did you use profiles?

- [ ] Profiles used?

### Relevant log output

```shell
[PRESENT-DAY PRESENT-TIME:40:59.691] [ui] [info] Restoring window size WxH
[PRESENT-DAY PRESENT-TIME:40:59.705] [ui] [info] WebRTC: initialised GStreamer 1.20.0
[PRESENT-DAY PRESENT-TIME:40:59.882] [ui] [info] Loaded jdenticon plugin.
[PRESENT-DAY PRESENT-TIME:41:00.088] [ui] [info] starting nheko 0.9.3
[PRESENT-DAY PRESENT-TIME:41:00.091] [ui] [info] User already signed in, showing chat page
[PRESENT-DAY PRESENT-TIME:41:00.092] [ui] [info] Switching to chat page
[PRESENT-DAY PRESENT-TIME:41:00.177] [qml] [warning] qrc:/qml/ChatPage.qml:104:17: QML RoomList: Binding loop detected for property "implicitWidth" (qrc:/qml/ChatPage.qml:104, )
[PRESENT-DAY PRESENT-TIME:41:00.177] [qml] [warning] qrc:/qml/ChatPage.qml:104:17: QML RoomList: Binding loop detected for property "implicitWidth" (qrc:/qml/ChatPage.qml:104, )
[PRESENT-DAY PRESENT-TIME:41:00.279] [db] [info] database ready
[PRESENT-DAY PRESENT-TIME:41:00.280] [db] [info] restoring state from cache
[PRESENT-DAY PRESENT-TIME:41:00.283] [crypto] [info] Could not find inbound megolm session (!ZzZzZZzZzZZZZZZzzZ:matrix.org, HNNNNNGGNGNGNGNNGNGNGNNGGGGNNGNGNGNGNGNGNGG, @hmmmst:matrix.org)
[PRESENT-DAY PRESENT-TIME:41:00.285] [crypto] [info] Could not find inbound megolm session (!YAWWWWnnnnnnWWWNZz:matrix.org, WhyAmIEvenDoingThisThisThatsFuckingStupidp, @ahyes:matrix.org)
[PRESENT-DAY PRESENT-TIME:41:00.297] [crypto] [info] Could not find inbound megolm session (!SoTiredHMMMstZZZZZ:matrix.org, XenomorphsEmergeFromWithinAndKilleverybodyH, @someuser:matrix.org)
[PRESENT-DAY PRESENT-TIME:41:00.304] [db] [info] Restored 70 rooms from cache
[PRESENT-DAY PRESENT-TIME:41:00.314] [net] [error] Failed to download {room1 url} : (connection: Couldn't resolve host name)
[PRESENT-DAY PRESENT-TIME:41:00.316] [net] [error] Failed to download {room2 url} : (connection: Couldn't resolve host name)
[PRESENT-DAY PRESENT-TIME:41:00.320] [net] [error] Failed to download {room3 url} : (connection: Couldn't resolve host name)
{...}
[PRESENT-DAY PRESENT-TIME:41:00.378] [db] [info] Invalidating self verification status
[PRESENT-DAY PRESENT-TIME:41:00.381] [crypto] [info] ed25519   : //WithTheAParamSpaceYo/uCanDoWondersAndHome
[PRESENT-DAY PRESENT-TIME:41:00.381] [crypto] [info] curve25519: tHisISperfectHash/ingAlgorithmAndYouMustUse
[PRESENT-DAY PRESENT-TIME:41:00.381] [crypto] [info] Online key backup disabled.
[PRESENT-DAY PRESENT-TIME:41:00.382] [net] [warning] failed to retrieve own profile info
[PRESENT-DAY PRESENT-TIME:41:00.382] [crypto] [warning] failed to update one-time keys: (connection: Couldn't resolve host name)
[PRESENT-DAY PRESENT-TIME:41:00.382] [net] [warning] failed to retrieve profile info for @daknig:matrix.org
[PRESENT-DAY PRESENT-TIME:41:00.383] [net] [warning] failed to query devices:  0
[PRESENT-DAY PRESENT-TIME:41:00.384] [qml] [warning] qrc:/qml/Avatar.qml:54:5: QML Image: Failed to download image: {room1 url} (qrc:/qml/Avatar.qml:54, )
[PRESENT-DAY PRESENT-TIME:41:00.384] [qml] [warning] qrc:/qml/Avatar.qml:54:5: QML Image: Failed to download image: {room2 url} (qrc:/qml/Avatar.qml:54, )
[PRESENT-DAY PRESENT-TIME:41:00.384] [qml] [warning] qrc:/qml/Avatar.qml:54:5: QML Image: Failed to download image: {room3 url} (qrc:/qml/Avatar.qml:54, )
[PRESENT-DAY PRESENT-TIME:41:00.385] [net] [warning] failed to query device keys:  0
[PRESENT-DAY PRESENT-TIME:41:00.385] [net] [error] sync error: (connection: Couldn't resolve host name)
[PRESENT-DAY PRESENT-TIME:41:02.485] [qml] [warning] QObject::killTimer: Timers cannot be stopped from another thread (:0, )
[PRESENT-DAY PRESENT-TIME:41:02.485] [qml] [warning] QObject::startTimer: Timers cannot be started from another thread (:0, )
[PRESENT-DAY PRESENT-TIME:41:04.661] [net] [warning] failed to stop typing notifications: 
[PRESENT-DAY PRESENT-TIME:41:05.613] [net] [error] sync error: (connection: Couldn't resolve host name)
[PRESENT-DAY PRESENT-TIME:41:08.656] [net] [warning] failed to stop typing notifications: 
[PRESENT-DAY PRESENT-TIME:41:08.657] [net] [warning] failed to stop typing notifications: 
[PRESENT-DAY PRESENT-TIME:41:08.658] [net] [warning] failed to send typing notification: 
[PRESENT-DAY PRESENT-TIME:41:08.663] [net] [warning] failed to stop typing notifications: 
[PRESENT-DAY PRESENT-TIME:41:09.302] [net] [warning] failed to stop typing notifications: 
[PRESENT-DAY PRESENT-TIME:41:09.304] [net] [warning] failed to stop typing notifications: 
[PRESENT-DAY PRESENT-TIME:41:09.305] [net] [warning] failed to stop typing notifications: 
[PRESENT-DAY PRESENT-TIME:41:09.305] [net] [warning] failed to stop typing notifications: 
[PRESENT-DAY PRESENT-TIME:41:09.306] [net] [warning] [metaClassofAnotherClassIsNotation] failed to send message:  0
[PRESENT-DAY PRESENT-TIME:41:09.745] [net] [warning] failed to stop typing notifications: 
[PRESENT-DAY PRESENT-TIME:41:09.746] [net] [warning] failed to stop typing notifications: 
[PRESENT-DAY PRESENT-TIME:41:09.747] [net] [warning] failed to stop typing notifications: 
[PRESENT-DAY PRESENT-TIME:41:09.748] [net] [warning] failed to send typing notification: 
[PRESENT-DAY PRESENT-TIME:41:10.330] [net] [warning] [WhatsEvenThisRoomSupposedToBeIDK0] failed to send message:  0
[PRESENT-DAY PRESENT-TIME:41:10.613] [net] [error] sync error: (connection: Couldn't resolve host name)
[PRESENT-DAY PRESENT-TIME:41:11.334] [net] [warning] [WhatsEvenThisRoomSupposedToBeIDK0] failed to send message:  0
[PRESENT-DAY PRESENT-TIME:41:12.347] [net] [warning] [WhatsEvenThisRoomSupposedToBeIDK0] failed to send message:  0
[PRESENT-DAY PRESENT-TIME:41:13.350] [net] [warning] [WhatsEvenThisRoomSupposedToBeIDK0] failed to send message:  0
[PRESENT-DAY PRESENT-TIME:41:14.082] [net] [warning] failed to stop typing notifications: 
[PRESENT-DAY PRESENT-TIME:41:14.082] [net] [warning] failed to stop typing notifications: 
[PRESENT-DAY PRESENT-TIME:41:14.083] [net] [warning] failed to stop typing notifications: 
[PRESENT-DAY PRESENT-TIME:41:14.084] [net] [warning] failed to stop typing notifications: 
[PRESENT-DAY PRESENT-TIME:41:14.363] [net] [warning] [WhatsEvenThisRoomSupposedToBeIDK0] failed to send message:  0
[PRESENT-DAY PRESENT-TIME:41:15.367] [net] [warning] [WhatsEvenThisRoomSupposedToBeIDK0] failed to send message:  0
[PRESENT-DAY PRESENT-TIME:41:15.613] [net] [info] connectivity lost
[PRESENT-DAY PRESENT-TIME:41:15.613] [net] [error] sync error: (connection: Couldn't resolve host name)
[PRESENT-DAY PRESENT-TIME:41:16.380] [net] [warning] [WhatsEvenThisRoomSupposedToBeIDK0] failed to send message:  0
[PRESENT-DAY PRESENT-TIME:41:17.383] [net] [warning] [WhatsEvenThisRoomSupposedToBeIDK0] failed to send message:  0
[PRESENT-DAY PRESENT-TIME:41:18.397] [net] [warning] [WhatsEvenThisRoomSupposedToBeIDK0] failed to send message:  0
[PRESENT-DAY PRESENT-TIME:41:19.401] [net] [warning] [WhatsEvenThisRoomSupposedToBeIDK0] failed to send message:  0
[PRESENT-DAY PRESENT-TIME:41:19.934] [net] [warning] failed to send typing notification: 
[PRESENT-DAY PRESENT-TIME:41:20.405] [net] [warning] [NobodyCriesInTheNhekoRoomEvert6gs] failed to send message:  0
[PRESENT-DAY PRESENT-TIME:41:20.611] [net] [error] sync error: (connection: Couldn't resolve host name)
[PRESENT-DAY PRESENT-TIME:41:21.413] [net] [warning] [NobodyCriesInTheNhekoRoomEvert6gs] failed to send message:  0
[PRESENT-DAY PRESENT-TIME:41:22.417] [net] [warning] [NobodyCriesInTheNhekoRoomEvert6gs] failed to send message:  0
[PRESENT-DAY PRESENT-TIME:41:23.430] [net] [warning] [NobodyCriesInTheNhekoRoomEvert6gs] failed to send message:  0
[PRESENT-DAY PRESENT-TIME:41:24.181] [net] [warning] failed to stop typing notifications: 
[PRESENT-DAY PRESENT-TIME:41:24.182] [net] [warning] failed to stop typing notifications: 
[PRESENT-DAY PRESENT-TIME:41:24.183] [ne
```

### Backtrace

```shell
(gdb) backtrace 
#0  0x00007f465f01d60c in __pthread_kill_implementation () at /lib64/libc.so.6
#1  0x00007f465efd0dc6 in raise () at /lib64/libc.so.6
#2  0x00007f465efa3833 in abort () at /lib64/libc.so.6
#3  0x00005613e7934978 in std::__replacement_assert(char const*, int, char const*, char const*)
    (__file=<optimized out>, __line=<optimized out>, __function=<optimized out>, __condition=<optimized out>)
    at /usr/include/c++/11/x86_64-redhat-linux/bits/c++config.h:2660
#4  0x00005613e79408cb in EventStore::EventStore(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, QObject*)::{lambda(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)#5}::operator()(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) const [clone .lto_priv.0] () at /usr/include/c++/11/optional:437
#5  0x00005613e7974062 in QtPrivate::FunctorCall<QtPrivate::IndexesList<0, 1>, QtPrivate::List<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocat--Ty--Type <RET> for more, q to quit, c to continue without paging--c
or<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, void, EventStore::EventStore(std::string, QObject*)::<lambda(std::string, std::string)> >::call (arg=<optimized out>, f=...) at /usr/include/qt5/QtCore/qobjectdefs_impl.h:146
#6  QtPrivate::Functor<EventStore::EventStore(std::string, QObject*)::<lambda(std::string, std::string)>, 2>::call<QtPrivate::List<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, void> (arg=<optimized out>, f=...) at /usr/include/qt5/QtCore/qobjectdefs_impl.h:256
#7  QtPrivate::QFunctorSlotObject<EventStore::EventStore(std::string, QObject*)::<lambda(std::string, std::string)>, 2, QtPrivate::List<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, void>::impl(int, QtPrivate::QSlotObjectBase *, QObject *, void **, bool *) (which=<optimized out>, this_=0x5613ebc07590, r=<optimized out>, a=<optimized out>, ret=<optimized out>) at /usr/include/qt5/QtCore/qobjectdefs_impl.h:443
#8  0x00007f465fabaf49 in QObject::event(QEvent*) () at /lib64/libQt5Core.so.5
#9  0x00007f466071e443 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /lib64/libQt5Widgets.so.5
#10 0x00007f465fa907d8 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /lib64/libQt5Core.so.5
#11 0x00007f465fa93d46 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () at /lib64/libQt5Core.so.5
#12 0x00007f465fae2117 in postEventSourceDispatch(_GSource*, int (*)(void*), void*) () at /lib64/libQt5Core.so.5
#13 0x00007f465f52b0af in g_main_context_dispatch () at /lib64/libglib-2.0.so.0
#14 0x00007f465f580308 in g_main_context_iterate.constprop () at /lib64/libglib-2.0.so.0
#15 0x00007f465f5288a3 in g_main_context_iteration () at /lib64/libglib-2.0.so.0
#16 0x00007f465fae1bb8 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib64/libQt5Core.so.5
#17 0x00007f465fa8f1e2 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib64/libQt5Core.so.5
#18 0x00007f465fa97724 in QCoreApplication::exec() () at /lib64/libQt5Core.so.5
#19 0x00005613e7902a13 in main(int, char**) (argc=<optimized out>, argv=<optimized out>) at /usr/src/debug/nheko-0.9.3-1.fc35.x86_64/src/main.cpp:358
```

**Comment by deepbluev7** [comment]
I can't reproduce this. Also the crash dump is exactly the same as for a bug I fixed already. Are you SURE it happens in the nightly?

**Comment by DaKnig** [comment]
just tested the flatpak version from this link:
https://matrix.neko.dev/_matrix/media/r0/download/neko.dev/RVlHVgZBuDxTYrYeNXotDBGd

crashes with the steps I described exactly

**Comment by DaKnig** [comment]
I have a terrible feeling that this might depend on a specific version of some dependency

**Comment by deepbluev7** [comment]
When installing a flatpak, you might have multiple versions installed at the same time, can you confirm the commit hash in the settings with me?

**Comment by DaKnig** [comment]
0.9.3-74712ff6

**Comment by DaKnig** [comment]
when I build nheko locally, and run it with the following command from build tree, it does not exhibit the issue:
`XDG_CACHE_HOME=/tmp/test/ XDG_CONFIG_HOME=/tmp/test/ XDG_DATA_HOME=/tmp/test/ ./nheko`

**Comment by deepbluev7** [comment]
Can you still reproduce this btw?

**Comment by DaKnig** [comment]
cannot reproduce on 0.10.2
