### ISSUE TITLE
Segfault when viewing any room

### ISSUE THREAD

**Issue by RunningDroid** [Nheko-Reborn/nheko#1083]
### Describe the bug

I successfully joined #pinenote:matrix.org via nheko, but when I go to view the room nheko segfaults.

### To Reproduce

1. Search for the #pinenote:matrix.org room
2. Join the room
3. Try to view the room
4. Watch nheko segfault

### What happened?

Nheko hung for like half a second, then disappeared.

### Expected behavior

I expected to view #pinenote:matrix.org

### Version

0.9.3

### Operating system

Linux

### Installation method

Some repository (AUR, homebrew, distribution repository, PPA, etc)

### Qt version

5.15.2

### C++ compiler

GCC 10.2.1pre1

### Desktop Environment

I3wm

### Did you use profiles?

- [ ] Profiles used?

### Relevant log output

The log file was empty, this is the output when running nheko from a terminal:
```
[2022-06-01 23:08:33.699] [ui] [info] Restoring window size 1366x726
[2022-06-01 23:08:33.718] [ui] [info] WebRTC: initialised GStreamer 1.20.1
[2022-06-01 23:08:33.799] [ui] [info] jdenticon plugin not found.
[2022-06-01 23:08:34.747] [ui] [info] starting nheko 0.9.3
[2022-06-01 23:08:34.749] [ui] [info] User already signed in, showing chat page
[2022-06-01 23:08:34.752] [ui] [info] Switching to chat page
[2022-06-01 23:08:35.160] [qml] [warning] qrc:/qml/ChatPage.qml:104:17: QML RoomList: Binding loop detected for property "implicitWidth" (qrc:/qml/ChatPage.qml:104, )
[2022-06-01 23:08:35.161] [qml] [warning] qrc:/qml/ChatPage.qml:104:17: QML RoomList: Binding loop detected for property "implicitWidth" (qrc:/qml/ChatPage.qml:104, )
[2022-06-01 23:08:37.768] [db] [info] database ready
[2022-06-01 23:08:37.769] [db] [info] restoring state from cache
[2022-06-01 23:08:37.801] [db] [info] Restored 43 rooms from cache
[2022-06-01 23:08:39.772] [db] [info] Invalidating self verification status
[2022-06-01 23:08:39.776] [crypto] [info] ed25519   : [redacted]
[2022-06-01 23:08:39.776] [crypto] [info] curve25519: [redacted]
[2022-06-01 23:08:39.776] [crypto] [info] Online key backup disabled.
[2022-06-01 23:08:40.138] [crypto] [info] Fetched server key count 50 signed_curve25519
[2022-06-01 23:08:41.040] [db] [info] Invalidating self verification status
[2022-06-01 23:08:41.078] [db] [info] Invalidating self verification status
[2022-06-01 23:08:41.804] [net] [info] TURN server(s) retrieved from homeserver:
[2022-06-01 23:08:41.804] [net] [info] username: 1654225721:@runningdroid:matrix.org
[2022-06-01 23:08:41.804] [net] [info] ttl: 86400 seconds
[2022-06-01 23:08:41.804] [net] [info] uri: turn:turn.matrix.org:3478?transport=udp
[2022-06-01 23:08:41.804] [net] [info] uri: turn:turn.matrix.org:3478?transport=tcp
[2022-06-01 23:08:41.804] [net] [info] uri: turns:turn.matrix.org:443?transport=tcp
Error: signal 11:
nheko(_Z17stacktraceHandleri+0x3b)[0x5591381bcb5b]
/usr/lib/libpthread.so.0(+0x13900)[0x7f247d2ef900]
nheko(_ZN8nlohmann10basic_jsonISt3mapSt6vectorNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEblmdSaNS_14adl_serializerES2_IhSaIhEEE10json_value7destroyENS_6detail7value_tE+0x3e5)[0x559137f677b5]
/usr/lib/libmatrix_client.so.0.7.0(_ZN3mtx4http6Client10read_eventERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES9_St8functionIFvRKSt8optionalINS0_11ClientErrorEEEEb+0x30d)[0x7f247fd01bad]
nheko(_ZN13TimelineModel9readEventERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0xbc)[0x559137fa228c]
nheko(_ZN13TimelineModel15setCurrentIndexEi+0x1fb)[0x559137fa370b]
nheko(_ZN13TimelineModel11qt_metacallEN11QMetaObject4CallEiPPv+0x8b)[0x5591381cc94b]
/usr/lib/libQt5Qml.so.5(_ZN3QV414QObjectWrapper11setPropertyEPNS_15ExecutionEngineEP7QObjectP16QQmlPropertyDataRKNS_5ValueE+0x552)[0x7f247f0c3a22]
/usr/lib/libQt5Qml.so.5(_ZN3QV414QObjectWrapper14setQmlPropertyEPNS_15ExecutionEngineEP15QQmlContextDataP7QObjectPNS_6StringENS0_12RevisionModeERKNS_5ValueE+0xe7)[0x7f247f0c48c7]
/usr/lib/libQt5Qml.so.5(_ZN3QV414QObjectWrapper10virtualPutEPNS_7ManagedENS_11PropertyKeyERKNS_5ValueEPS4_+0x145)[0x7f247f0c4a65]
/usr/lib/libQt5Qml.so.5(_ZN3QV46Object26virtualResolveLookupSetterEPS0_PNS_15ExecutionEngineEPNS_6LookupERKNS_5ValueE+0x1db)[0x7f247f08fe0b]
/usr/lib/libQt5Qml.so.5(+0x1b12b8)[0x7f247f0dd2b8]
/usr/lib/libQt5Qml.so.5(+0x1b50e7)[0x7f247f0e10e7]
/usr/lib/libQt5Qml.so.5(_ZN3QV48Function4callEPKNS_5ValueES3_iPKNS_16ExecutionContextE+0x16d)[0x7f247f07c92d]
/usr/lib/libQt5Qml.so.5(_ZN24QQmlJavaScriptExpression8evaluateEPN3QV48CallDataEPb+0x225)[0x7f247f1f36a5]
/usr/lib/libQt5Qml.so.5(_ZN25QQmlBoundSignalExpression8evaluateEPPv+0x33b)[0x7f247f1a786b]
/usr/lib/libQt5Qml.so.5(+0x27bd50)[0x7f247f1a7d50]
/usr/lib/libQt5Qml.so.5(_ZN12QQmlNotifier10emitNotifyEP20QQmlNotifierEndpointPPv+0x23d)[0x7f247f1d748d]
/usr/lib/libQt5Core.so.5(+0x2e5305)[0x7f247dcf2305]
/usr/lib/libQt5Quick.so.5(+0x302210)[0x7f247f688210]
/usr/lib/libQt5Quick.so.5(_ZN14QQuickItemView8setModelERK8QVariant+0x535)[0x7f247f68b555]
/usr/lib/libQt5Qml.so.5(_ZN19QQmlPropertyPrivate5writeEP7QObjectRK16QQmlPropertyDataRK8QVariantP15QQmlContextData6QFlagsINS2_9WriteFlagEE+0xc28)[0x7f247f196e78]
/usr/lib/libQt5Qml.so.5(_ZN11QQmlBinding9slowWriteERK16QQmlPropertyDataS2_RKN3QV45ValueEb6QFlagsINS0_9WriteFlagEE+0x4d0)[0x7f247f1f99f0]
/usr/lib/libQt5Qml.so.5(+0x2cf130)[0x7f247f1fb130]
/usr/lib/libQt5Qml.so.5(+0x2d076e)[0x7f247f1fc76e]
/usr/lib/libQt5Qml.so.5(_ZN11QQmlBinding6updateE6QFlagsIN16QQmlPropertyData9WriteFlagEE+0x214)[0x7f247f1fa424]
/usr/lib/libQt5Qml.so.5(_ZN12QQmlNotifier10emitNotifyEP20QQmlNotifierEndpointPPv+0x23d)[0x7f247f1d748d]
/usr/lib/libQt5Core.so.5(+0x2e5305)[0x7f247dcf2305]
/usr/lib/libQt5Qml.so.5(_ZN17QQmlVMEMetaObject16writeVarPropertyEiRKN3QV45ValueE+0xd1)[0x7f247f1869a1]
/usr/lib/libQt5Qml.so.5(_ZN11QQmlBinding9slowWriteERK16QQmlPropertyDataS2_RKN3QV45ValueEb6QFlagsINS0_9WriteFlagEE+0x1ad)[0x7f247f1f96cd]
/usr/lib/libQt5Qml.so.5(+0x2cf130)[0x7f247f1fb130]
/usr/lib/libQt5Qml.so.5(+0x2d076e)[0x7f247f1fc76e]
/usr/lib/libQt5Qml.so.5(_ZN11QQmlBinding6updateE6QFlagsIN16QQmlPropertyData9WriteFlagEE+0x214)[0x7f247f1fa424]
/usr/lib/libQt5Qml.so.5(_ZN12QQmlNotifier10emitNotifyEP20QQmlNotifierEndpointPPv+0x23d)[0x7f247f1d748d]
/usr/lib/libQt5Core.so.5(+0x2e5305)[0x7f247dcf2305]
/usr/lib/libQt5Core.so.5(+0x2e5776)[0x7f247dcf2776]
nheko(_ZN13RoomlistModel14setCurrentRoomE7QString+0x2ad)[0x559137ff783d]
nheko(+0x525c69)[0x5591381cfc69]
nheko(_ZN21FilteredRoomlistModel11qt_metacallEN11QMetaObject4CallEiPPv+0xd3)[0x5591381d01e3]
/usr/lib/libQt5Qml.so.5(+0x2ab9dd)[0x7f247f1d79dd]
/usr/lib/libQt5Qml.so.5(+0x194f7e)[0x7f247f0c0f7e]
/usr/lib/libQt5Qml.so.5(_ZNK3QV413QObjectMethod12callInternalEPKNS_5ValueES3_i+0x5ca)[0x7f247f0c2dca]
/usr/lib/libQt5Qml.so.5(+0x1b25bf)[0x7f247f0de5bf]
/usr/lib/libQt5Qml.so.5(+0x1b50e7)[0x7f247f0e10e7]
/usr/lib/libQt5Qml.so.5(_ZN3QV48Function4callEPKNS_5ValueES3_iPKNS_16ExecutionContextE+0x16d)[0x7f247f07c92d]
/usr/lib/libQt5Qml.so.5(_ZN24QQmlJavaScriptExpression8evaluateEPN3QV48CallDataEPb+0x225)[0x7f247f1f36a5]
/usr/lib/libQt5Qml.so.5(_ZN25QQmlBoundSignalExpression8evaluateEPPv+0x33b)[0x7f247f1a786b]
/usr/lib/libQt5Qml.so.5(+0x27bd50)[0x7f247f1a7d50]
/usr/lib/libQt5Qml.so.5(_ZN12QQmlNotifier10emitNotifyEP20QQmlNotifierEndpointPPv+0x23d)[0x7f247f1d748d]
/usr/lib/libQt5Core.so.5(+0x2e5305)[0x7f247dcf2305]
Error: signal 6:
nheko(_Z17stacktraceHandleri+0x3b)[0x5591381bcb5b]
/usr/lib/libc.so.6(+0x3d000)[0x7f247d153000]
/usr/lib/libpthread.so.0(raise+0x141)[0x7f247d2ef7a1]
nheko(_Z17stacktraceHandleri+0xf1)[0x5591381bcc11]
/usr/lib/libpthread.so.0(+0x13900)[0x7f247d2ef900]
nheko(_ZN8nlohmann10basic_jsonISt3mapSt6vectorNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEblmdSaNS_14adl_serializerES2_IhSaIhEEE10json_value7destroyENS_6detail7value_tE+0x3e5)[0x559137f677b5]
/usr/lib/libmatrix_client.so.0.7.0(_ZN3mtx4http6Client10read_eventERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES9_St8functionIFvRKSt8optionalINS0_11ClientErrorEEEEb+0x30d)[0x7f247fd01bad]
nheko(_ZN13TimelineModel9readEventERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0xbc)[0x559137fa228c]
nheko(_ZN13TimelineModel15setCurrentIndexEi+0x1fb)[0x559137fa370b]
nheko(_ZN13TimelineModel11qt_metacallEN11QMetaObject4CallEiPPv+0x8b)[0x5591381cc94b]
/usr/lib/libQt5Qml.so.5(_ZN3QV414QObjectWrapper11setPropertyEPNS_15ExecutionEngineEP7QObjectP16QQmlPropertyDataRKNS_5ValueE+0x552)[0x7f247f0c3a22]
/usr/lib/libQt5Qml.so.5(_ZN3QV414QObjectWrapper14setQmlPropertyEPNS_15ExecutionEngineEP15QQmlContextDataP7QObjectPNS_6StringENS0_12RevisionModeERKNS_5ValueE+0xe7)[0x7f247f0c48c7]
/usr/lib/libQt5Qml.so.5(_ZN3QV414QObjectWrapper10virtualPutEPNS_7ManagedENS_11PropertyKeyERKNS_5ValueEPS4_+0x145)[0x7f247f0c4a65]
/usr/lib/libQt5Qml.so.5(_ZN3QV46Object26virtualResolveLookupSetterEPS0_PNS_15ExecutionEngineEPNS_6LookupERKNS_5ValueE+0x1db)[0x7f247f08fe0b]
/usr/lib/libQt5Qml.so.5(+0x1b12b8)[0x7f247f0dd2b8]
/usr/lib/libQt5Qml.so.5(+0x1b50e7)[0x7f247f0e10e7]
/usr/lib/libQt5Qml.so.5(_ZN3QV48Function4callEPKNS_5ValueES3_iPKNS_16ExecutionContextE+0x16d)[0x7f247f07c92d]
/usr/lib/libQt5Qml.so.5(_ZN24QQmlJavaScriptExpression8evaluateEPN3QV48CallDataEPb+0x225)[0x7f247f1f36a5]
/usr/lib/libQt5Qml.so.5(_ZN25QQmlBoundSignalExpression8evaluateEPPv+0x33b)[0x7f247f1a786b]
/usr/lib/libQt5Qml.so.5(+0x27bd50)[0x7f247f1a7d50]
/usr/lib/libQt5Qml.so.5(_ZN12QQmlNotifier10emitNotifyEP20QQmlNotifierEndpointPPv+0x23d)[0x7f247f1d748d]
/usr/lib/libQt5Core.so.5(+0x2e5305)[0x7f247dcf2305]
/usr/lib/libQt5Quick.so.5(+0x302210)[0x7f247f688210]
/usr/lib/libQt5Quick.so.5(_ZN14QQuickItemView8setModelERK8QVariant+0x535)[0x7f247f68b555]
/usr/lib/libQt5Qml.so.5(_ZN19QQmlPropertyPrivate5writeEP7QObjectRK16QQmlPropertyDataRK8QVariantP15QQmlContextData6QFlagsINS2_9WriteFlagEE+0xc28)[0x7f247f196e78]
/usr/lib/libQt5Qml.so.5(_ZN11QQmlBinding9slowWriteERK16QQmlPropertyDataS2_RKN3QV45ValueEb6QFlagsINS0_9WriteFlagEE+0x4d0)[0x7f247f1f99f0]
/usr/lib/libQt5Qml.so.5(+0x2cf130)[0x7f247f1fb130]
/usr/lib/libQt5Qml.so.5(+0x2d076e)[0x7f247f1fc76e]
/usr/lib/libQt5Qml.so.5(_ZN11QQmlBinding6updateE6QFlagsIN16QQmlPropertyData9WriteFlagEE+0x214)[0x7f247f1fa424]
/usr/lib/libQt5Qml.so.5(_ZN12QQmlNotifier10emitNotifyEP20QQmlNotifierEndpointPPv+0x23d)[0x7f247f1d748d]
/usr/lib/libQt5Core.so.5(+0x2e5305)[0x7f247dcf2305]
/usr/lib/libQt5Qml.so.5(_ZN17QQmlVMEMetaObject16writeVarPropertyEiRKN3QV45ValueE+0xd1)[0x7f247f1869a1]
/usr/lib/libQt5Qml.so.5(_ZN11QQmlBinding9slowWriteERK16QQmlPropertyDataS2_RKN3QV45ValueEb6QFlagsINS0_9WriteFlagEE+0x1ad)[0x7f247f1f96cd]
/usr/lib/libQt5Qml.so.5(+0x2cf130)[0x7f247f1fb130]
/usr/lib/libQt5Qml.so.5(+0x2d076e)[0x7f247f1fc76e]
/usr/lib/libQt5Qml.so.5(_ZN11QQmlBinding6updateE6QFlagsIN16QQmlPropertyData9WriteFlagEE+0x214)[0x7f247f1fa424]
/usr/lib/libQt5Qml.so.5(_ZN12QQmlNotifier10emitNotifyEP20QQmlNotifierEndpointPPv+0x23d)[0x7f247f1d748d]
/usr/lib/libQt5Core.so.5(+0x2e5305)[0x7f247dcf2305]
/usr/lib/libQt5Core.so.5(+0x2e5776)[0x7f247dcf2776]
nheko(_ZN13RoomlistModel14setCurrentRoomE7QString+0x2ad)[0x559137ff783d]
nheko(+0x525c69)[0x5591381cfc69]
nheko(_ZN21FilteredRoomlistModel11qt_metacallEN11QMetaObject4CallEiPPv+0xd3)[0x5591381d01e3]
/usr/lib/libQt5Qml.so.5(+0x2ab9dd)[0x7f247f1d79dd]
/usr/lib/libQt5Qml.so.5(+0x194f7e)[0x7f247f0c0f7e]
/usr/lib/libQt5Qml.so.5(_ZNK3QV413QObjectMethod12callInternalEPKNS_5ValueES3_i+0x5ca)[0x7f247f0c2dca]
/usr/lib/libQt5Qml.so.5(+0x1b25bf)[0x7f247f0de5bf]
/usr/lib/libQt5Qml.so.5(+0x1b50e7)[0x7f247f0e10e7]
/usr/lib/libQt5Qml.so.5(_ZN3QV48Function4callEPKNS_5ValueES3_iPKNS_16ExecutionContextE+0x16d)[0x7f247f07c92d]
/usr/lib/libQt5Qml.so.5(_ZN24QQmlJavaScriptExpression8evaluateEPN3QV48CallDataEPb+0x225)[0x7f247f1f36a5]
/usr/lib/libQt5Qml.so.5(_ZN25QQmlBoundSignalExpression8evaluateEPPv+0x33b)[0x7f247f1a786b]
[1]    15749 IOT instruction  nheko
```

### Backtrace

```shell
Starting program: /usr/bin/nheko 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib64/libthread_db.so.1".
[New Thread 0x7ffff0fdc640 (LWP 11535)]
[New Thread 0x7fffebd65640 (LWP 11536)]
[New Thread 0x7fffeb564640 (LWP 11537)]
[New Thread 0x7fffe97c2640 (LWP 11538)]
[New Thread 0x7fffe8fc1640 (LWP 11539)]
[New Thread 0x7fffe3bff640 (LWP 11540)]
[New Thread 0x7fffe335b640 (LWP 11543)]
[New Thread 0x7fffe2b5a640 (LWP 11544)]
[New Thread 0x7fffe1ec0640 (LWP 11545)]
[Thread 0x7fffe1ec0640 (LWP 11545) exited]
[New Thread 0x7fffe1ec0640 (LWP 11546)]
[Thread 0x7fffe1ec0640 (LWP 11546) exited]
[New Thread 0x7fffe1ec0640 (LWP 11547)]
[New Thread 0x7ff7b3fff640 (LWP 11548)]
[New Thread 0x7ff7b37fe640 (LWP 11549)]
[New Thread 0x7ff7b2597640 (LWP 11550)]
[New Thread 0x7ff7b1d96640 (LWP 11551)]
[New Thread 0x7ff7b1595640 (LWP 11552)]
[New Thread 0x7ff7b09cc640 (LWP 11553)]
[New Thread 0x7ff79bfff640 (LWP 11554)]
[New Thread 0x7ff79b7fe640 (LWP 11555)]
[New Thread 0x7ff79affd640 (LWP 11556)]
[New Thread 0x7ff79a7fc640 (LWP 11557)]
[New Thread 0x7ff799ffb640 (LWP 11558)]
[New Thread 0x7ff7997fa640 (LWP 11559)]
[Thread 0x7ff7b09cc640 (LWP 11553) exited]
[Thread 0x7ff7997fa640 (LWP 11559) exited]
[Thread 0x7ff79affd640 (LWP 11556) exited]
[Thread 0x7ff799ffb640 (LWP 11558) exited]
[Thread 0x7ff79a7fc640 (LWP 11557) exited]
[Thread 0x7ff79b7fe640 (LWP 11555) exited]
[Thread 0x7ff79bfff640 (LWP 11554) exited]

Thread 1 "nheko" received signal SIGSEGV, Segmentation fault.
0x00005555558117b5 in nlohmann::basic_json<std::map, std::vector, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, long, unsigned long, double, std::allocator, nlohmann::adl_serializer, std::vector<unsigned char, std::allocator<unsigned char> > >::json_value::destroy(nlohmann::detail::value_t) ()

Thread 1 (Thread 0x7ffff353df80 (LWP 11531) "nheko"):
#0  0x00005555558117b5 in nlohmann::basic_json<std::map, std::vector, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, long, unsigned long, double, std::allocator, nlohmann::adl_serializer, std::vector<unsigned char, std::allocator<unsigned char> > >::json_value::destroy(nlohmann::detail::value_t) ()
#1  0x00007ffff7d38bad in mtx::http::Client::read_event(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::function<void (std::optional<mtx::http::ClientError> const&)>, bool) () from /usr/lib/libmatrix_client.so.0.7.0
#2  0x000055555584c28c in TimelineModel::readEvent(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
#3  0x000055555584d70b in TimelineModel::setCurrentIndex(int) ()
#4  0x0000555555a7694b in TimelineModel::qt_metacall(QMetaObject::Call, int, void**) ()
#5  0x00007ffff70faa22 in QV4::QObjectWrapper::setProperty(QV4::ExecutionEngine*, QObject*, QQmlPropertyData*, QV4::Value const&) () from /usr/lib/libQt5Qml.so.5
#6  0x00007ffff70fb8c7 in QV4::QObjectWrapper::setQmlProperty(QV4::ExecutionEngine*, QQmlContextData*, QObject*, QV4::String*, QV4::QObjectWrapper::RevisionMode, QV4::Value const&) () from /usr/lib/libQt5Qml.so.5
#7  0x00007ffff70fba65 in QV4::QObjectWrapper::virtualPut(QV4::Managed*, QV4::PropertyKey, QV4::Value const&, QV4::Value*) () from /usr/lib/libQt5Qml.so.5
#8  0x00007ffff70c6e0b in QV4::Object::virtualResolveLookupSetter(QV4::Object*, QV4::ExecutionEngine*, QV4::Lookup*, QV4::Value const&) () from /usr/lib/libQt5Qml.so.5
#9  0x00007ffff71142b8 in ?? () from /usr/lib/libQt5Qml.so.5
#10 0x00007ffff71180e7 in ?? () from /usr/lib/libQt5Qml.so.5
#11 0x00007ffff70b392d in QV4::Function::call(QV4::Value const*, QV4::Value const*, int, QV4::ExecutionContext const*) () from /usr/lib/libQt5Qml.so.5
#12 0x00007ffff722a6a5 in QQmlJavaScriptExpression::evaluate(QV4::CallData*, bool*) () from /usr/lib/libQt5Qml.so.5
#13 0x00007ffff71de86b in QQmlBoundSignalExpression::evaluate(void**) () from /usr/lib/libQt5Qml.so.5
#14 0x00007ffff71ded50 in ?? () from /usr/lib/libQt5Qml.so.5
#15 0x00007ffff720e48d in QQmlNotifier::emitNotify(QQmlNotifierEndpoint*, void**) () from /usr/lib/libQt5Qml.so.5
#16 0x00007ffff5d29305 in ?? () from /usr/lib/libQt5Core.so.5
#17 0x00007ffff76bf210 in ?? () from /usr/lib/libQt5Quick.so.5
#18 0x00007ffff76c2555 in QQuickItemView::setModel(QVariant const&) () from /usr/lib/libQt5Quick.so.5
#19 0x00007ffff71cde78 in QQmlPropertyPrivate::write(QObject*, QQmlPropertyData const&, QVariant const&, QQmlContextData*, QFlags<QQmlPropertyData::WriteFlag>) () from /usr/lib/libQt5Qml.so.5
#20 0x00007ffff72309f0 in QQmlBinding::slowWrite(QQmlPropertyData const&, QQmlPropertyData const&, QV4::Value const&, bool, QFlags<QQmlPropertyData::WriteFlag>) () from /usr/lib/libQt5Qml.so.5
#21 0x00007ffff7232130 in ?? () from /usr/lib/libQt5Qml.so.5
#22 0x00007ffff723376e in ?? () from /usr/lib/libQt5Qml.so.5
#23 0x00007ffff7231424 in QQmlBinding::update(QFlags<QQmlPropertyData::WriteFlag>) () from /usr/lib/libQt5Qml.so.5
#24 0x00007ffff720e48d in QQmlNotifier::emitNotify(QQmlNotifierEndpoint*, void**) () from /usr/lib/libQt5Qml.so.5
#25 0x00007ffff5d29305 in ?? () from /usr/lib/libQt5Core.so.5
#26 0x00007ffff71bd9a1 in QQmlVMEMetaObject::writeVarProperty(int, QV4::Value const&) () from /usr/lib/libQt5Qml.so.5
#27 0x00007ffff72306cd in QQmlBinding::slowWrite(QQmlPropertyData const&, QQmlPropertyData const&, QV4::Value const&, bool, QFlags<QQmlPropertyData::WriteFlag>) () from /usr/lib/libQt5Qml.so.5
#28 0x00007ffff7232130 in ?? () from /usr/lib/libQt5Qml.so.5
#29 0x00007ffff723376e in ?? () from /usr/lib/libQt5Qml.so.5
#30 0x00007ffff7231424 in QQmlBinding::update(QFlags<QQmlPropertyData::WriteFlag>) () from /usr/lib/libQt5Qml.so.5
#31 0x00007ffff720e48d in QQmlNotifier::emitNotify(QQmlNotifierEndpoint*, void**) () from /usr/lib/libQt5Qml.so.5
#32 0x00007ffff5d29305 in ?? () from /usr/lib/libQt5Core.so.5
#33 0x00007ffff5d29776 in ?? () from /usr/lib/libQt5Core.so.5
#34 0x00005555558a183d in RoomlistModel::setCurrentRoom(QString) ()
#35 0x0000555555a79c69 in ?? ()
#36 0x0000555555a7a1e3 in FilteredRoomlistModel::qt_metacall(QMetaObject::Call, int, void**) ()
#37 0x00007ffff720e9dd in ?? () from /usr/lib/libQt5Qml.so.5
#38 0x00007ffff70f7f7e in ?? () from /usr/lib/libQt5Qml.so.5
#39 0x00007ffff70f9dca in QV4::QObjectMethod::callInternal(QV4::Value const*, QV4::Value const*, int) const () from /usr/lib/libQt5Qml.so.5
#40 0x00007ffff71155bf in ?? () from /usr/lib/libQt5Qml.so.5
#41 0x00007ffff71180e7 in ?? () from /usr/lib/libQt5Qml.so.5
#42 0x00007ffff70b392d in QV4::Function::call(QV4::Value const*, QV4::Value const*, int, QV4::ExecutionContext const*) () from /usr/lib/libQt5Qml.so.5
#43 0x00007ffff722a6a5 in QQmlJavaScriptExpression::evaluate(QV4::CallData*, bool*) () from /usr/lib/libQt5Qml.so.5
#44 0x00007ffff71de86b in QQmlBoundSignalExpression::evaluate(void**) () from /usr/lib/libQt5Qml.so.5
#45 0x00007ffff71ded50 in ?? () from /usr/lib/libQt5Qml.so.5
#46 0x00007ffff720e48d in QQmlNotifier::emitNotify(QQmlNotifierEndpoint*, void**) () from /usr/lib/libQt5Qml.so.5
#47 0x00007ffff5d29305 in ?? () from /usr/lib/libQt5Core.so.5
#48 0x00007fffe1573f51 in QQuickAbstractButtonPrivate::handleRelease(QPointF const&) () from /usr/lib/qt5/qml/Qt/labs/platform/../../../../../libQt5QuickTemplates2.so.5
#49 0x00007fffe1590ff9 in QQuickControl::mouseReleaseEvent(QMouseEvent*) () from /usr/lib/qt5/qml/Qt/labs/platform/../../../../../libQt5QuickTemplates2.so.5
#50 0x00007ffff7603648 in QQuickItem::event(QEvent*) () from /usr/lib/libQt5Quick.so.5
#51 0x00007ffff699b17f in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#52 0x00007ffff5cf319a in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib/libQt5Core.so.5
#53 0x00007ffff761f5d4 in QQuickWindowPrivate::deliverMouseEvent(QQuickPointerMouseEvent*) () from /usr/lib/libQt5Quick.so.5
#54 0x00007ffff762090b in QQuickWindowPrivate::deliverPointerEvent(QQuickPointerEvent*) () from /usr/lib/libQt5Quick.so.5
#55 0x00007ffff62ac825 in QWindow::event(QEvent*) () from /usr/lib/libQt5Gui.so.5
#56 0x00007ffff699b17f in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#57 0x00007ffff5cf319a in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib/libQt5Core.so.5
#58 0x00007ffff62a05c3 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () from /usr/lib/libQt5Gui.so.5
#59 0x00007ffff62766bc in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Gui.so.5
#60 0x00007ffff13ec40a in ?? () from /usr/lib/qt5/plugins/platforms/../../../libQt5XcbQpa.so.5
#61 0x00007ffff578bf3b in g_main_context_dispatch () from /usr/lib/libglib-2.0.so.0
#62 0x00007ffff578c1e8 in ?? () from /usr/lib/libglib-2.0.so.0
#63 0x00007ffff578c29f in g_main_context_iteration () from /usr/lib/libglib-2.0.so.0
#64 0x00007ffff5d4a57f in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Core.so.5
#65 0x00007ffff5cf1b4b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Core.so.5
#66 0x00007ffff5cf9dd0 in QCoreApplication::exec() () from /usr/lib/libQt5Core.so.5
#67 0x00005555557a7340 in main ()
quit
```

**Comment by RunningDroid** [comment]
As an additional note, nheko apparently updates the read status of the room before segfaulting.

**Comment by deepbluev7** [comment]
Does it keep segfaulting or did that only happen once?

**Comment by RunningDroid** [comment]
It keeps segfaulting; apparently it segfaults on viewing any room, not just #pinenote:matrix.org.

**Comment by deepbluev7** [comment]
Are you on arch? Have you tried rebuilding Nheko (and mtxclient)?

**Comment by RunningDroid** [comment]
I'm on Void, rebuilding both fixed the segfault
