### ISSUE TITLE
nheko crashes after update with QML libraries on the top of the backtrace

### ISSUE THREAD

**Issue by jmglogow** [Nheko-Reborn/nheko#1132]
### Describe the bug

It has happened multiple times for me when using a new nheko version (compiled from git on Debian Bullseye), that it crashes in very early startup. I just saw that the crash isn't anymore in my shell scrollbuffer, so I can't copy the backtrace (including a SIGSEGV and a SIGABRT - multiple threads?), and since I removed `~/.cache/nheko` to log is unfortunately also gone. But it ended in some `libQt5Qml*` and removing `~/.cache/nheko` always has fixed the problem (maybe just removing `qmlcache` would have worked too).

So I suggest to add some `version` file to the cache to check against the current nheko version and eventually discard the QML cache on startup.

### To Reproduce

I don't really have steps to reproduce. It didn't happen on all updates, but the update from 0.9.3 to 0.10.0 (both build as Debian packages from git) triggered it this time.

### What happened?

nheko crashes very early, just a few lines of log output in the terminal on startup and long backtraces ending in Qml libraries.

### Expected behavior

No crash after update.

### Version

 nheko_0.10.0-32-gb5942423

### Operating system

Linux

### Installation method

Local build

### Qt version

5.15.2+dfsg-9

### C++ compiler

gcc (Debian 10.2.1-6) 10.2.1 20210110

### Desktop Environment

KDE

### Did you use profiles?

- [ ] Profiles used?

### Relevant log output

```shell
n/a
```

### Backtrace

```shell
n/a
```

**Comment by barathrm** [comment]
It sounds like I hit the same bug trying to test 0.10.2 for openSUSE Tumbleweed. Removing `~/.cache/nheko` is a workaround. What's the right way to prevent this? Looks like the default constructor for QQmlType segfaults. This is the backtrace from the thread which segfaults.

```
#0  QQmlType::QQmlType(QQmlType const&) (this=this@entry=0x7fffc4de73f0) at /usr/src/debug/qtdeclarative-everywhere-src-5.15.7+kde18/src/qml/qml/qqmltype.cpp:121
#1  0x00007ffff723e3a5 in QQmlPropertyCacheCreator<QQmlTypeCompiler>::propertyCacheForObject(QmlIR::Object const*, QQmlBindingInstantiationContext const&, QQmlError*) const
    (this=this@entry=0x7fffc4de7790, obj=obj@entry=0x7fffa44e0cc8, context=..., error=error@entry=0x7fffc4de7488) at ../../include/QtQml/5.15.7/QtQml/private/../../../../../../src/qml/qml/qqmlpropertycachecreator_p.h:310
#2  0x00007ffff72411c0 in QQmlPropertyCacheCreator<QQmlTypeCompiler>::buildMetaObjectRecursively(int, QQmlBindingInstantiationContext const&, QQmlPropertyCacheCreator<QQmlTypeCompiler>::VMEMetaObjectIsRequired)
    (this=this@entry=0x7fffc4de7790, objectIndex=<optimized out>, context=..., isVMERequired=isVMERequired@entry=QQmlPropertyCacheCreator<QQmlTypeCompiler>::VMEMetaObjectIsRequired::Maybe)
    at ../../include/QtQml/5.15.7/QtQml/private/../../../../../../src/qml/qml/qqmlpropertycachecreator_p.h:264
#3  0x00007ffff72413d9 in QQmlPropertyCacheCreator<QQmlTypeCompiler>::buildMetaObjectRecursively(int, QQmlBindingInstantiationContext const&, QQmlPropertyCacheCreator<QQmlTypeCompiler>::VMEMetaObjectIsRequired)
    (this=this@entry=0x7fffc4de7790, objectIndex=objectIndex@entry=0, context=<optimized out>, isVMERequired=isVMERequired@entry=QQmlPropertyCacheCreator<QQmlTypeCompiler>::VMEMetaObjectIsRequired::Maybe) at /usr/include/qt5/QtCore/qendian.h:290
#4  0x00007ffff7242238 in QQmlPropertyCacheCreator<QQmlTypeCompiler>::buildMetaObjects() (this=this@entry=0x7fffc4de7790) at ../../include/QtQml/5.15.7/QtQml/private/../../../../../../src/qml/qml/qqmlpropertycachecreator_p.h:215
#5  0x00007ffff723cbcd in QQmlTypeCompiler::compile() (this=this@entry=0x7fffc4de7900) at /usr/src/debug/qtdeclarative-everywhere-src-5.15.7+kde18/src/qml/qml/qqmltypecompiler.cpp:85
#6  0x00007ffff718d9f5 in QQmlTypeData::compile(QQmlRefPointer<QQmlTypeNameCache> const&, QV4::ResolvedTypeReferenceMap*, std::function<QByteArray ()> const&)
    (this=this@entry=0x7fffa4463b70, typeNameCache=..., resolvedTypeCache=resolvedTypeCache@entry=0x7fffc4de7a00, dependencyHasher=...) at /usr/src/debug/qtdeclarative-everywhere-src-5.15.7+kde18/src/qml/qml/qqmltypedata.cpp:774
#7  0x00007ffff7193a03 in QQmlTypeData::done() (this=0x7fffa4463b70) at /usr/src/debug/qtdeclarative-everywhere-src-5.15.7+kde18/src/qml/qml/qqmltypedata.cpp:451
#8  0x00007ffff7181805 in QQmlDataBlob::tryDone() (this=0x7fffa4463b70) at /usr/src/debug/qtdeclarative-everywhere-src-5.15.7+kde18/src/qml/qml/qqmldatablob.cpp:524
#9  QQmlDataBlob::tryDone() (this=0x7fffa4463b70) at /usr/src/debug/qtdeclarative-everywhere-src-5.15.7+kde18/src/qml/qml/qqmldatablob.cpp:515
#10 0x00007ffff71e0d3c in QQmlTypeLoader::setData(QQmlDataBlob*, QQmlDataBlob::SourceCodeData const&) (this=this@entry=0x555555f1dac8, blob=blob@entry=0x7fffa4463b70, d=...)
    at /usr/src/debug/qtdeclarative-everywhere-src-5.15.7+kde18/src/qml/qml/qqmltypeloader.cpp:457
#11 0x00007ffff71e1442 in QQmlTypeLoader::setData(QQmlDataBlob*, QString const&) (this=this@entry=0x555555f1dac8, blob=blob@entry=0x7fffa4463b70, fileName=...) at /usr/src/debug/qtdeclarative-everywhere-src-5.15.7+kde18/src/qml/qml/qqmltypeloader.cpp:437
#12 0x00007ffff71e27bf in QQmlTypeLoader::loadThread(QQmlDataBlob*) (this=this@entry=0x555555f1dac8, blob=blob@entry=0x7fffa4463b70) at /usr/src/debug/qtdeclarative-everywhere-src-5.15.7+kde18/src/qml/qml/qqmltypeloader.cpp:299
#13 0x00007ffff71e2c2c in PlainLoader::loadThread(QQmlTypeLoader*, QQmlDataBlob*) const (blob=0x7fffa4463b70, loader=0x555555f1dac8, this=<optimized out>) at /usr/src/debug/qtdeclarative-everywhere-src-5.15.7+kde18/src/qml/qml/qqmltypeloader.cpp:146
#14 QQmlTypeLoader::doLoad<PlainLoader>(PlainLoader const&, QQmlDataBlob*, QQmlTypeLoader::Mode) (loader=<optimized out>, mode=QQmlTypeLoader::PreferSynchronous, blob=0x7fffa4463b70, this=0x555555f1dac8)
    at /usr/src/debug/qtdeclarative-everywhere-src-5.15.7+kde18/src/qml/qml/qqmltypeloader.cpp:205
#15 QQmlTypeLoader::load(QQmlDataBlob*, QQmlTypeLoader::Mode) (this=0x555555f1dac8, blob=0x7fffa4463b70, mode=QQmlTypeLoader::PreferSynchronous) at /usr/src/debug/qtdeclarative-everywhere-src-5.15.7+kde18/src/qml/qml/qqmltypeloader.cpp:237
#16 0x00007ffff71e34d0 in QQmlTypeLoader::getType(QUrl const&, QQmlTypeLoader::Mode) (this=this@entry=0x555555f1dac8, unNormalizedUrl=..., mode=mode@entry=QQmlTypeLoader::PreferSynchronous)
    at /usr/src/debug/qtdeclarative-everywhere-src-5.15.7+kde18/src/qml/qml/qqmltypeloader.cpp:825
#17 0x00007ffff7192acc in QQmlTypeData::resolveTypes() (this=this@entry=0x555556455ee0) at /usr/src/debug/qtdeclarative-everywhere-src-5.15.7+kde18/src/qml/qml/qqmltypedata.cpp:873
#18 0x00007ffff71956e0 in QQmlTypeData::allDependenciesDone() (this=<optimized out>) at /usr/src/debug/qtdeclarative-everywhere-src-5.15.7+kde18/src/qml/qml/qqmltypedata.cpp:743
#19 0x00007ffff71e0fd9 in QQmlTypeLoader::setData(QQmlDataBlob*, QQmlDataBlob::SourceCodeData const&) (this=this@entry=0x555555f1dac8, blob=blob@entry=0x555556455ee0, d=...)
    at /usr/src/debug/qtdeclarative-everywhere-src-5.15.7+kde18/src/qml/qml/qqmltypeloader.cpp:450
#20 0x00007ffff71e1442 in QQmlTypeLoader::setData(QQmlDataBlob*, QString const&) (this=this@entry=0x555555f1dac8, blob=blob@entry=0x555556455ee0, fileName=...) at /usr/src/debug/qtdeclarative-everywhere-src-5.15.7+kde18/src/qml/qml/qqmltypeloader.cpp:437
#21 0x00007ffff71e27bf in QQmlTypeLoader::loadThread(QQmlDataBlob*) (this=0x555555f1dac8, blob=blob@entry=0x555556455ee0) at /usr/src/debug/qtdeclarative-everywhere-src-5.15.7+kde18/src/qml/qml/qqmltypeloader.cpp:299
#22 0x00007ffff719d38d in QQmlTypeLoaderThread::loadThread(QQmlDataBlob*) (this=<optimized out>, b=0x555556455ee0) at /usr/src/debug/qtdeclarative-everywhere-src-5.15.7+kde18/src/qml/qml/qqmltypeloaderthread.cpp:162
#23 0x00007ffff725b24c in QQmlThreadPrivate::threadEvent() (this=0x5555560e98e0) at /usr/src/debug/qtdeclarative-everywhere-src-5.15.7+kde18/src/qml/qml/ftw/qqmlthread.cpp:198
#24 0x00007ffff725b9b2 in QQmlThreadPrivate::event(QEvent*) (this=0x5555560e98e0, e=0x555556478d60) at /usr/src/debug/qtdeclarative-everywhere-src-5.15.7+kde18/src/qml/qml/ftw/qqmlthread.cpp:142
#25 0x00007ffff69243fe in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /lib64/libQt5Widgets.so.5
#26 0x00007ffff5bbf128 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /lib64/libQt5Core.so.5
#27 0x00007ffff5bc20c1 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () at /lib64/libQt5Core.so.5
#28 0x00007ffff5c17353 in  () at /lib64/libQt5Core.so.5
#29 0x00007ffff5625a90 in g_main_context_dispatch () at /lib64/libglib-2.0.so.0
#30 0x00007ffff5625e48 in  () at /lib64/libglib-2.0.so.0
#31 0x00007ffff5625edc in g_main_context_iteration () at /lib64/libglib-2.0.so.0
#32 0x00007ffff5c16b56 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib64/libQt5Core.so.5
#33 0x00007ffff5bbdb9b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib64/libQt5Core.so.5
#34 0x00007ffff59d7c47 in QThread::exec() () at /lib64/libQt5Core.so.5
#35 0x00007ffff725af05 in QQmlThreadPrivate::run() (this=0x5555560e98e0) at /usr/src/debug/qtdeclarative-everywhere-src-5.15.7+kde18/src/qml/qml/ftw/qqmlthread.cpp:155
#36 0x00007ffff59d8e3d in  () at /lib64/libQt5Core.so.5
#37 0x00007ffff50f898d in start_thread () at /lib64/libc.so.6
#38 0x00007ffff517f380 in clone3 () at /lib64/libc.so.6
```
