### ISSUE TITLE
segfault when searching for `0.10.2` in nheko room

### ISSUE THREAD

**Issue by tastytea** [Nheko-Reborn/nheko#1219]
### Describe the bug

nheko reproducibly segfaults when searching for `0.10.2` in the nheko Matrix room.

### To Reproduce

1. use nheko commit 76347f1c
2. go to nheko Matrix room
3. search for `0.10.2`
4. segfault

### Version

0.10.2-76347f1c

### Operating system

Linux

### Installation method

Some repository (AUR, homebrew, distribution repository, PPA, etc)

### Qt version

5.15.5

### C++ compiler

gcc-11.3.0

### Did you use profiles?

- [X] Profiles used?

### Backtrace

```shell
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `nheko --profile tastytea.de'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  QQmlInterceptorMetaObject::intercept () at /var/tmp/portage/dev-qt/qtdeclarative-5.15.5/work/qtdeclarative-everywhere-src-5.15.5/src/qml/qml/qqmlvmemetaobject.cpp:309
[Current thread is 1 (Thread 0x7f3042f45f80 (LWP 16972))]

Thread 17 (Thread 0x7f27ff61f640 (LWP 17048)):
#0  0x00007f30406b853d in select () at /lib64/libc.so.6
#1  0x00007f301ebdf291 in  () at /usr/lib64/libnvidia-glcore.so.470.141.03
#2  0x00007f301ebdcdbd in  () at /usr/lib64/libnvidia-glcore.so.470.141.03
#3  0x00007f304063f84a in start_thread () at /lib64/libc.so.6
#4  0x00007f30406c2cec in clone3 () at /lib64/libc.so.6

Thread 16 (Thread 0x7f27e95d7640 (LWP 17123)):
#0  0x00007f304063c45a in __futex_abstimed_wait_common () at /lib64/libc.so.6
#1  0x00007f304063ec00 in pthread_cond_wait () at /lib64/libc.so.6
#2  0x00007f3040ee8b33 in QWaitConditionPrivate::wait(QDeadlineTimer) () at /var/tmp/portage/dev-qt/qtcore-5.15.5-r3/work/qtbase-everywhere-src-5.15.5/src/corelib/thread/qwaitcondition_unix.cpp:146
#3  QWaitCondition::wait(QMutex*, QDeadlineTimer) () at /var/tmp/portage/dev-qt/qtcore-5.15.5-r3/work/qtbase-everywhere-src-5.15.5/src/corelib/thread/qwaitcondition_unix.cpp:225
#4  0x00007f3042894a33 in QSGRenderThreadEventQueue::takeEvent(bool) () at /var/tmp/portage/dev-qt/qtdeclarative-5.15.5/work/qtdeclarative-everywhere-src-5.15.5/src/quick/scenegraph/qsgthreadedrenderloop.cpp:257
#5  QSGRenderThread::processEventsAndWaitForMore() () at /var/tmp/portage/dev-qt/qtdeclarative-5.15.5/work/qtdeclarative-everywhere-src-5.15.5/src/quick/scenegraph/qsgthreadedrenderloop.cpp:936
#6  0x00007f3042896dc9 in QSGRenderThread::run() () at /var/tmp/portage/dev-qt/qtdeclarative-5.15.5/work/qtdeclarative-everywhere-src-5.15.5/src/quick/scenegraph/qsgthreadedrenderloop.cpp:1053
#7  0x00007f3040ee3529 in QThreadPrivate::start(void*) () at /var/tmp/portage/dev-qt/qtcore-5.15.5-r3/work/qtbase-everywhere-src-5.15.5/src/corelib/thread/qthread_unix.cpp:331
#8  0x00007f304063f84a in start_thread () at /lib64/libc.so.6
#9  0x00007f30406c2cec in clone3 () at /lib64/libc.so.6

Thread 15 (Thread 0x7f300bfff640 (LWP 17033)):
#0  0x00007f30406c2336 in epoll_wait () at /lib64/libc.so.6
#1  0x00007f30430acf63 in epoll_dispatch () at /var/tmp/portage/dev-libs/libevent-2.1.12/work/libevent-2.1.12-stable/epoll.c:465
#2  0x00007f30430a30c9 in event_base_loop () at /var/tmp/portage/dev-libs/libevent-2.1.12/work/libevent-2.1.12-stable/event.c:1992
#3  0x00007f30409845c0 in execute_native_thread_routine() () at /var/tmp/portage/sys-devel/gcc-11.3.0/work/gcc-11.3.0/libstdc++-v3/src/c++11/thread.cc:82
#4  0x00007f304063f84a in start_thread () at /lib64/libc.so.6
#5  0x00007f30406c2cec in clone3 () at /lib64/libc.so.6

Thread 14 (Thread 0x7f301d5fe640 (LWP 17000)):
#0  0x00007f30406b5e3f in poll () at /lib64/libc.so.6
#1  0x00007f3040574f32 in poll () at /usr/include/bits/poll2.h:39
#2  poll_func () at ../pulseaudio-16.1/src/pulse/thread-mainloop.c:70
#3  0x00007f3040566e11 in pa_mainloop_poll () at ../pulseaudio-16.1/src/pulse/mainloop.c:863
#4  0x00007f304056744f in pa_mainloop_iterate () at ../pulseaudio-16.1/src/pulse/mainloop.c:945
#5  0x00007f30405674f8 in pa_mainloop_run () at ../pulseaudio-16.1/src/pulse/mainloop.c:963
#6  0x00007f3040575001 in thread () at ../pulseaudio-16.1/src/pulse/thread-mainloop.c:101
#7  0x00007f303da8ac56 in internal_thread_func () at ../pulseaudio-16.1/src/pulsecore/thread-posix.c:81
#8  0x00007f304063f84a in start_thread () at /lib64/libc.so.6
#9  0x00007f30406c2cec in clone3 () at /lib64/libc.so.6

Thread 13 (Thread 0x7f27eb21f640 (LWP 17112)):
#0  0x00007f304063c45a in __futex_abstimed_wait_common () at /lib64/libc.so.6
#1  0x00007f304063ec00 in pthread_cond_wait () at /lib64/libc.so.6
#2  0x00007f3040ee8b33 in QWaitConditionPrivate::wait(QDeadlineTimer) () at /var/tmp/portage/dev-qt/qtcore-5.15.5-r3/work/qtbase-everywhere-src-5.15.5/src/corelib/thread/qwaitcondition_unix.cpp:146
#3  QWaitCondition::wait(QMutex*, QDeadlineTimer) () at /var/tmp/portage/dev-qt/qtcore-5.15.5-r3/work/qtbase-everywhere-src-5.15.5/src/corelib/thread/qwaitcondition_unix.cpp:225
#4  0x00007f3042894a33 in QSGRenderThreadEventQueue::takeEvent(bool) () at /var/tmp/portage/dev-qt/qtdeclarative-5.15.5/work/qtdeclarative-everywhere-src-5.15.5/src/quick/scenegraph/qsgthreadedrenderloop.cpp:257
#5  QSGRenderThread::processEventsAndWaitForMore() () at /var/tmp/portage/dev-qt/qtdeclarative-5.15.5/work/qtdeclarative-everywhere-src-5.15.5/src/quick/scenegraph/qsgthreadedrenderloop.cpp:936
#6  0x00007f3042896dc9 in QSGRenderThread::run() () at /var/tmp/portage/dev-qt/qtdeclarative-5.15.5/work/qtdeclarative-everywhere-src-5.15.5/src/quick/scenegraph/qsgthreadedrenderloop.cpp:1053
#7  0x00007f3040ee3529 in QThreadPrivate::start(void*) () at /var/tmp/portage/dev-qt/qtcore-5.15.5-r3/work/qtbase-everywhere-src-5.15.5/src/corelib/thread/qthread_unix.cpp:331
#8  0x00007f304063f84a in start_thread () at /lib64/libc.so.6
#9  0x00007f30406c2cec in clone3 () at /lib64/libc.so.6

Thread 12 (Thread 0x7f300992f640 (LWP 17036)):
#0  0x00007f30406b5e3f in poll () at /lib64/libc.so.6
#1  0x00007f3040b52c2e in g_main_context_poll () at ../glib-2.72.3/glib/gmain.c:4516
#2  g_main_context_iterate () at ../glib-2.72.3/glib/gmain.c:4206
#3  0x00007f3040b52d3f in g_main_context_iteration () at ../glib-2.72.3/glib/gmain.c:4276
#4  0x00007f30410d8c04 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /var/tmp/portage/dev-qt/qtcore-5.15.5-r3/work/qtbase-everywhere-src-5.15.5/src/corelib/kernel/qeventdispatcher_glib.cpp:423
#5  0x00007f3041088373 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /var/tmp/portage/dev-qt/qtcore-5.15.5-r3/work/qtbase-everywhere-src-5.15.5/src/corelib/kernel/qeventloop.cpp:232
#6  0x00007f3040ee240a in QThread::exec() () at /var/tmp/portage/dev-qt/qtcore-5.15.5-r3/work/qtbase-everywhere-src-5.15.5/src/corelib/thread/qthread.cpp:547
#7  0x00007f30427e3356 in QQuickPixmapReader::run() () at /var/tmp/portage/dev-qt/qtdeclarative-5.15.5/work/qtdeclarative-everywhere-src-5.15.5/src/quick/util/qquickpixmapcache.cpp:1024
#8  0x00007f3040ee3529 in QThreadPrivate::start(void*) () at /var/tmp/portage/dev-qt/qtcore-5.15.5-r3/work/qtbase-everywhere-src-5.15.5/src/corelib/thread/qthread_unix.cpp:331
#9  0x00007f304063f84a in start_thread () at /lib64/libc.so.6
#10 0x00007f30406c2cec in clone3 () at /lib64/libc.so.6

Thread 11 (Thread 0x7f30297ff640 (LWP 16990)):
#0  0x00007f30406b5e3f in poll () at /lib64/libc.so.6
#1  0x00007f3040b52c2e in g_main_context_poll () at ../glib-2.72.3/glib/gmain.c:4516
#2  g_main_context_iterate () at ../glib-2.72.3/glib/gmain.c:4206
#3  0x00007f3040b52d3f in g_main_context_iteration () at ../glib-2.72.3/glib/gmain.c:4276
#4  0x00007f30410d8c04 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /var/tmp/portage/dev-qt/qtcore-5.15.5-r3/work/qtbase-everywhere-src-5.15.5/src/corelib/kernel/qeventdispatcher_glib.cpp:423
#5  0x00007f3041088373 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /var/tmp/portage/dev-qt/qtcore-5.15.5-r3/work/qtbase-everywhere-src-5.15.5/src/corelib/kernel/qeventloop.cpp:232
#6  0x00007f3040ee240a in QThread::exec() () at /var/tmp/portage/dev-qt/qtcore-5.15.5-r3/work/qtbase-everywhere-src-5.15.5/src/corelib/thread/qthread.cpp:547
#7  0x00007f3042539105 in QQmlThreadPrivate::run() () at /var/tmp/portage/dev-qt/qtdeclarative-5.15.5/work/qtdeclarative-everywhere-src-5.15.5/src/qml/qml/ftw/qqmlthread.cpp:155
#8  0x00007f3040ee3529 in QThreadPrivate::start(void*) () at /var/tmp/portage/dev-qt/qtcore-5.15.5-r3/work/qtbase-everywhere-src-5.15.5/src/corelib/thread/qthread_unix.cpp:331
#9  0x00007f304063f84a in start_thread () at /lib64/libc.so.6
#10 0x00007f30406c2cec in clone3 () at /lib64/libc.so.6

Thread 10 (Thread 0x7f301cdfd640 (LWP 17019)):
#0  0x00007f30406b5e3f in poll () at /lib64/libc.so.6
#1  0x00007f3040b52c2e in g_main_context_poll () at ../glib-2.72.3/glib/gmain.c:4516
#2  g_main_context_iterate () at ../glib-2.72.3/glib/gmain.c:4206
#3  0x00007f3040b52f43 in g_main_loop_run () at ../glib-2.72.3/glib/gmain.c:4411
#4  0x00007f302847fd32 in provider_thread () at ../gst-plugins-good-1.20.3/sys/v4l2/gstv4l2deviceprovider.c:406
#5  0x00007f3040b7bced in g_thread_proxy () at ../glib-2.72.3/glib/gthread.c:827
#6  0x00007f304063f84a in start_thread () at /lib64/libc.so.6
#7  0x00007f30406c2cec in clone3 () at /lib64/libc.so.6

Thread 9 (Thread 0x7f303b557640 (LWP 16984)):
#0  0x00007f304063c45a in __futex_abstimed_wait_common () at /lib64/libc.so.6
#1  0x00007f304063ef04 in pthread_cond_timedwait () at /lib64/libc.so.6
#2  0x00007f3040ee8aa2 in QWaitConditionPrivate::wait_relative(QDeadlineTimer) () at /var/tmp/portage/dev-qt/qtcore-5.15.5-r3/work/qtbase-everywhere-src-5.15.5/src/corelib/thread/qwaitcondition_unix.cpp:136
#3  QWaitConditionPrivate::wait(QDeadlineTimer) () at /var/tmp/portage/dev-qt/qtcore-5.15.5-r3/work/qtbase-everywhere-src-5.15.5/src/corelib/thread/qwaitcondition_unix.cpp:144
#4  QWaitCondition::wait(QMutex*, QDeadlineTimer) () at /var/tmp/portage/dev-qt/qtcore-5.15.5-r3/work/qtbase-everywhere-src-5.15.5/src/corelib/thread/qwaitcondition_unix.cpp:225
#5  0x00007f3040ee6473 in QThreadPoolThread::run() () at /var/tmp/portage/dev-qt/qtcore-5.15.5-r3/work/qtbase-everywhere-src-5.15.5/src/corelib/thread/qthreadpool.cpp:140
#6  0x00007f3040ee3529 in QThreadPrivate::start(void*) () at /var/tmp/portage/dev-qt/qtcore-5.15.5-r3/work/qtbase-everywhere-src-5.15.5/src/corelib/thread/qthread_unix.cpp:331
#7  0x00007f304063f84a in start_thread () at /lib64/libc.so.6
#8  0x00007f30406c2cec in clone3 () at /lib64/libc.so.6

Thread 8 (Thread 0x7f303c7bf640 (LWP 16974)):
#0  0x00007f30406b5e3f in poll () at /lib64/libc.so.6
#1  0x00007f3040acccc4 in poll () at /usr/include/bits/poll2.h:39
#2  _xcb_conn_wait () at /var/tmp/portage/x11-libs/libxcb-1.15-r1/work/libxcb-1.15/src/xcb_conn.c:508
#3  0x00007f3040ace6a2 in xcb_wait_for_event () at /var/tmp/portage/x11-libs/libxcb-1.15-r1/work/libxcb-1.15/src/xcb_in.c:703
#4  0x00007f303c9eca20 in QXcbEventQueue::run() () at /var/tmp/portage/dev-qt/qtgui-5.15.5-r2/work/qtbase-everywhere-src-5.15.5/src/plugins/platforms/xcb/qxcbeventqueue.cpp:228
#5  0x00007f3040ee3529 in QThreadPrivate::start(void*) () at /var/tmp/portage/dev-qt/qtcore-5.15.5-r3/work/qtbase-everywhere-src-5.15.5/src/corelib/thread/qthread_unix.cpp:331
#6  0x00007f304063f84a in start_thread () at /lib64/libc.so.6
#7  0x00007f30406c2cec in clone3 () at /lib64/libc.so.6

Thread 7 (Thread 0x7f3039ac7640 (LWP 16982)):
#0  0x00007f304063c45a in __futex_abstimed_wait_common () at /lib64/libc.so.6
#1  0x00007f304063ef04 in pthread_cond_timedwait () at /lib64/libc.so.6
#2  0x00007f3040ee8aa2 in QWaitConditionPrivate::wait_relative(QDeadlineTimer) () at /var/tmp/portage/dev-qt/qtcore-5.15.5-r3/work/qtbase-everywhere-src-5.15.5/src/corelib/thread/qwaitcondition_unix.cpp:136
#3  QWaitConditionPrivate::wait(QDeadlineTimer) () at /var/tmp/portage/dev-qt/qtcore-5.15.5-r3/work/qtbase-everywhere-src-5.15.5/src/corelib/thread/qwaitcondition_unix.cpp:144
#4  QWaitCondition::wait(QMutex*, QDeadlineTimer) () at /var/tmp/portage/dev-qt/qtcore-5.15.5-r3/work/qtbase-everywhere-src-5.15.5/src/corelib/thread/qwaitcondition_unix.cpp:225
#5  0x00007f3040ee6473 in QThreadPoolThread::run() () at /var/tmp/portage/dev-qt/qtcore-5.15.5-r3/work/qtbase-everywhere-src-5.15.5/src/corelib/thread/qthreadpool.cpp:140
#6  0x00007f3040ee3529 in QThreadPrivate::start(void*) () at /var/tmp/portage/dev-qt/qtcore-5.15.5-r3/work/qtbase-everywhere-src-5.15.5/src/corelib/thread/qthread_unix.cpp:331
#7  0x00007f304063f84a in start_thread () at /lib64/libc.so.6
#8  0x00007f30406c2cec in clone3 () at /lib64/libc.so.6

Thread 6 (Thread 0x7f27fd3c7640 (LWP 17107)):
#0  0x00007f304063c45a in __futex_abstimed_wait_common () at /lib64/libc.so.6
#1  0x00007f304063ec00 in pthread_cond_wait () at /lib64/libc.so.6
#2  0x00007f3040ee8b33 in QWaitConditionPrivate::wait(QDeadlineTimer) () at /var/tmp/portage/dev-qt/qtcore-5.15.5-r3/work/qtbase-everywhere-src-5.15.5/src/corelib/thread/qwaitcondition_unix.cpp:146
#3  QWaitCondition::wait(QMutex*, QDeadlineTimer) () at /var/tmp/portage/dev-qt/qtcore-5.15.5-r3/work/qtbase-everywhere-src-5.15.5/src/corelib/thread/qwaitcondition_unix.cpp:225
#4  0x00007f3042894a33 in QSGRenderThreadEventQueue::takeEvent(bool) () at /var/tmp/portage/dev-qt/qtdeclarative-5.15.5/work/qtdeclarative-everywhere-src-5.15.5/src/quick/scenegraph/qsgthreadedrenderloop.cpp:257
#5  QSGRenderThread::processEventsAndWaitForMore() () at /var/tmp/portage/dev-qt/qtdeclarative-5.15.5/work/qtdeclarative-everywhere-src-5.15.5/src/quick/scenegraph/qsgthreadedrenderloop.cpp:936
#6  0x00007f3042896dc9 in QSGRenderThread::run() () at /var/tmp/portage/dev-qt/qtdeclarative-5.15.5/work/qtdeclarative-everywhere-src-5.15.5/src/quick/scenegraph/qsgthreadedrenderloop.cpp:1053
#7  0x00007f3040ee3529 in QThreadPrivate::start(void*) () at /var/tmp/portage/dev-qt/qtcore-5.15.5-r3/work/qtbase-everywhere-src-5.15.5/src/corelib/thread/qthread_unix.cpp:331
#8  0x00007f304063f84a in start_thread () at /lib64/libc.so.6
#9  0x00007f30406c2cec in clone3 () at /lib64/libc.so.6

Thread 5 (Thread 0x7f3009027640 (LWP 17042)):
#0  0x00007f304063c45a in __futex_abstimed_wait_common () at /lib64/libc.so.6
#1  0x00007f304063ec00 in pthread_cond_wait () at /lib64/libc.so.6
#2  0x00007f3040ee8b33 in QWaitConditionPrivate::wait(QDeadlineTimer) () at /var/tmp/portage/dev-qt/qtcore-5.15.5-r3/work/qtbase-everywhere-src-5.15.5/src/corelib/thread/qwaitcondition_unix.cpp:146
#3  QWaitCondition::wait(QMutex*, QDeadlineTimer) () at /var/tmp/portage/dev-qt/qtcore-5.15.5-r3/work/qtbase-everywhere-src-5.15.5/src/corelib/thread/qwaitcondition_unix.cpp:225
#4  0x00007f3042894a33 in QSGRenderThreadEventQueue::takeEvent(bool) () at /var/tmp/portage/dev-qt/qtdeclarative-5.15.5/work/qtdeclarative-everywhere-src-5.15.5/src/quick/scenegraph/qsgthreadedrenderloop.cpp:257
#5  QSGRenderThread::processEventsAndWaitForMore() () at /var/tmp/portage/dev-qt/qtdeclarative-5.15.5/work/qtdeclarative-everywhere-src-5.15.5/src/quick/scenegraph/qsgthreadedrenderloop.cpp:936
#6  0x00007f3042896dc9 in QSGRenderThread::run() () at /var/tmp/portage/dev-qt/qtdeclarative-5.15.5/work/qtdeclarative-everywhere-src-5.15.5/src/quick/scenegraph/qsgthreadedrenderloop.cpp:1053
#7  0x00007f3040ee3529 in QThreadPrivate::start(void*) () at /var/tmp/portage/dev-qt/qtcore-5.15.5-r3/work/qtbase-everywhere-src-5.15.5/src/corelib/thread/qthread_unix.cpp:331
#8  0x00007f304063f84a in start_thread () at /lib64/libc.so.6
#9  0x00007f30406c2cec in clone3 () at /lib64/libc.so.6

Thread 4 (Thread 0x7f302ad7d640 (LWP 16985)):
#0  0x00007f304063c45a in __futex_abstimed_wait_common () at /lib64/libc.so.6
#1  0x00007f304063ef04 in pthread_cond_timedwait () at /lib64/libc.so.6
#2  0x00007f3040ee8aa2 in QWaitConditionPrivate::wait_relative(QDeadlineTimer) () at /var/tmp/portage/dev-qt/qtcore-5.15.5-r3/work/qtbase-everywhere-src-5.15.5/src/corelib/thread/qwaitcondition_unix.cpp:136
#3  QWaitConditionPrivate::wait(QDeadlineTimer) () at /var/tmp/portage/dev-qt/qtcore-5.15.5-r3/work/qtbase-everywhere-src-5.15.5/src/corelib/thread/qwaitcondition_unix.cpp:144
#4  QWaitCondition::wait(QMutex*, QDeadlineTimer) () at /var/tmp/portage/dev-qt/qtcore-5.15.5-r3/work/qtbase-everywhere-src-5.15.5/src/corelib/thread/qwaitcondition_unix.cpp:225
#5  0x00007f3040ee6473 in QThreadPoolThread::run() () at /var/tmp/portage/dev-qt/qtcore-5.15.5-r3/work/qtbase-everywhere-src-5.15.5/src/corelib/thread/qthreadpool.cpp:140
#6  0x00007f3040ee3529 in QThreadPrivate::start(void*) () at /var/tmp/portage/dev-qt/qtcore-5.15.5-r3/work/qtbase-everywhere-src-5.15.5/src/corelib/thread/qthread_unix.cpp:331
#7  0x00007f304063f84a in start_thread () at /lib64/libc.so.6
#8  0x00007f30406c2cec in clone3 () at /lib64/libc.so.6

Thread 3 (Thread 0x7f301ddff640 (LWP 16991)):
#0  0x00007f30406b5e3f in poll () at /lib64/libc.so.6
#1  0x00007f3040b52c2e in g_main_context_poll () at ../glib-2.72.3/glib/gmain.c:4516
#2  g_main_context_iterate () at ../glib-2.72.3/glib/gmain.c:4206
#3  0x00007f3040b52d3f in g_main_context_iteration () at ../glib-2.72.3/glib/gmain.c:4276
#4  0x00007f30410d8c04 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /var/tmp/portage/dev-qt/qtcore-5.15.5-r3/work/qtbase-everywhere-src-5.15.5/src/corelib/kernel/qeventdispatcher_glib.cpp:423
#5  0x00007f3041088373 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /var/tmp/portage/dev-qt/qtcore-5.15.5-r3/work/qtbase-everywhere-src-5.15.5/src/corelib/kernel/qeventloop.cpp:232
#6  0x00007f3040ee240a in QThread::exec() () at /var/tmp/portage/dev-qt/qtcore-5.15.5-r3/work/qtbase-everywhere-src-5.15.5/src/corelib/thread/qthread.cpp:547
#7  0x00007f30421a74cf in QDBusConnectionManager::run() () at /var/tmp/portage/dev-qt/qtdbus-5.15.5-r1/work/qtbase-everywhere-src-5.15.5/src/dbus/qdbusconnection.cpp:179
#8  0x00007f3040ee3529 in QThreadPrivate::start(void*) () at /var/tmp/portage/dev-qt/qtcore-5.15.5-r3/work/qtbase-everywhere-src-5.15.5/src/corelib/thread/qthread_unix.cpp:331
#9  0x00007f304063f84a in start_thread () at /lib64/libc.so.6
#10 0x00007f30406c2cec in clone3 () at /lib64/libc.so.6

Thread 2 (Thread 0x7f303a44f640 (LWP 16983)):
#0  0x00007f304063c45a in __futex_abstimed_wait_common () at /lib64/libc.so.6
#1  0x00007f304063ef04 in pthread_cond_timedwait () at /lib64/libc.so.6
#2  0x00007f3040ee8aa2 in QWaitConditionPrivate::wait_relative(QDeadlineTimer) () at /var/tmp/portage/dev-qt/qtcore-5.15.5-r3/work/qtbase-everywhere-src-5.15.5/src/corelib/thread/qwaitcondition_unix.cpp:136
#3  QWaitConditionPrivate::wait(QDeadlineTimer) () at /var/tmp/portage/dev-qt/qtcore-5.15.5-r3/work/qtbase-everywhere-src-5.15.5/src/corelib/thread/qwaitcondition_unix.cpp:144
#4  QWaitCondition::wait(QMutex*, QDeadlineTimer) () at /var/tmp/portage/dev-qt/qtcore-5.15.5-r3/work/qtbase-everywhere-src-5.15.5/src/corelib/thread/qwaitcondition_unix.cpp:225
#5  0x00007f3040ee6473 in QThreadPoolThread::run() () at /var/tmp/portage/dev-qt/qtcore-5.15.5-r3/work/qtbase-everywhere-src-5.15.5/src/corelib/thread/qthreadpool.cpp:140
#6  0x00007f3040ee3529 in QThreadPrivate::start(void*) () at /var/tmp/portage/dev-qt/qtcore-5.15.5-r3/work/qtbase-everywhere-src-5.15.5/src/corelib/thread/qthread_unix.cpp:331
#7  0x00007f304063f84a in start_thread () at /lib64/libc.so.6
#8  0x00007f30406c2cec in clone3 () at /lib64/libc.so.6

Thread 1 (Thread 0x7f3042f45f80 (LWP 16972)):
#0  QQmlInterceptorMetaObject::intercept(QMetaObject::Call, int, void**) () at /var/tmp/portage/dev-qt/qtdeclarative-5.15.5/work/qtdeclarative-everywhere-src-5.15.5/src/qml/qml/qqmlvmemetaobject.cpp:309
#1  0x00007f304248242c in QQmlVMEMetaObject::metaCall(QObject*, QMetaObject::Call, int, void**) () at /var/tmp/portage/dev-qt/qtdeclarative-5.15.5/work/qtdeclarative-everywhere-src-5.15.5/src/qml/qml/qqmlvmemetaobject.cpp:680
#2  0x00007f30423b7c95 in QQmlPropertyData::readProperty(QObject*, void*) const () at /var/tmp/portage/dev-qt/qtdeclarative-5.15.5/work/qtdeclarative-everywhere-src-5.15.5/include/QtQml/5.15.5/QtQml/private/../../../../../src/qml/qml/qqmlpropertydata_p.h:357
#3  loadProperty() () at /var/tmp/portage/dev-qt/qtdeclarative-5.15.5/work/qtdeclarative-everywhere-src-5.15.5/src/qml/jsruntime/qv4qobjectwrapper.cpp:152
#4  0x00007f3008708c0f in  ()
#5  0x0000000000000000 in  ()
```

**Comment by deepbluev7** [comment]
Hm, I can't reproduce this and the dump doesn't look that specific.

**Comment by tastytea** [comment]
Uhh, now i can't reproduce it myself anymore. 🥴 I'm gonna close this since it seems to be impossible to figure out what went wrong.
