### ISSUE TITLE
SIGSEGV on message edit

### ISSUE THREAD

**Issue by pizdjuk** [Nheko-Reborn/nheko#1469]
### Describe the bug

```
[2023-05-30 15:13:11.681] [net] [info] ttl: 3600 seconds
[2023-05-30 15:13:11.681] [net] [info] uri: turn:ru-matrix.org?transport=udp
[2023-05-30 15:13:11.681] [net] [info] uri: turn:ru-matrix.org?transport=tcp
[2023-05-30 15:13:11.861] [qml] [warning] QPainter::begin: Paint device returned engine == 0, type: 2 (:0, )
[2023-05-30 15:13:11.861] [qml] [warning] QPainter::setCompositionMode: Painter not active (:0, )
[2023-05-30 15:13:11.861] [qml] [warning] QPainter::end: Painter not active, aborted (:0, )
[2023-05-30 15:13:11.872] [qml] [warning] qrc:/qml/Avatar.qml:55:5: QML Image: Failed to get image from provider: image://colorimage/?#f4f5f8?radius=100 (qrc:/qml/Avatar.qml:55, )
[2023-05-30 15:13:11.878] [qml] [warning] QPainter::begin: Paint device returned engine == 0, type: 2 (:0, )
[2023-05-30 15:13:11.878] [qml] [warning] QPainter::setCompositionMode: Painter not active (:0, )
[2023-05-30 15:13:11.878] [qml] [warning] QPainter::end: Painter not active, aborted (:0, )
[2023-05-30 15:13:11.881] [qml] [warning] qrc:/qml/Avatar.qml:55:5: QML Image: Failed to get image from provider: image://colorimage/?#828284?radius=100 (qrc:/qml/Avatar.qml:55, )
[2023-05-30 15:13:14.678] [qml] [warning] qrc:/qml/ReplyPopup.qml:23:5: QML Reply: Binding loop detected for property "implicitWidth" (qrc:/qml/ReplyPopup.qml:23, )
[2023-05-30 15:13:16.018] [qml] [warning] qrc:/qml/delegates/TextMessage.qml:46: TypeError: Cannot read property 'width' of null (qrc:/qml/delegates/TextMessage.qml:46, )
[2023-05-30 15:13:16.021] [qml] [warning] qrc:/qml/ReplyPopup.qml:23:5: QML Reply: Binding loop detected for property "implicitWidth" (qrc:/qml/ReplyPopup.qml:23, )
/usr/include/c++/12.2.0/optional:477: constexpr _Tp& std::_Optional_base_impl<_Tp, _Dp>::_M_get() [with _Tp = int; _Dp = std::_Optional_base<int, true, true>]: Assertion 'this->_M_is_engaged()' failed.
Error: signal 6:
io.github.NhekoReborn.Nheko(+0x589b00)[0x55eaf54a7b00]
/usr/lib/x86_64-linux-gnu/libc.so.6(+0x3f0c0)[0x7fa5e64890c0]
/usr/lib/x86_64-linux-gnu/libc.so.6(+0x91184)[0x7fa5e64db184]
/usr/lib/x86_64-linux-gnu/libc.so.6(raise+0x1e)[0x7fa5e648900e]
/usr/lib/x86_64-linux-gnu/libc.so.6(abort+0xd7)[0x7fa5e64727fc]
/usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0xe1f9d)[0x7fa5e683ef9d]
io.github.NhekoReborn.Nheko(+0x25e8c2)[0x55eaf517c8c2]
io.github.NhekoReborn.Nheko(+0x25ea84)[0x55eaf517ca84]
/usr/lib/x86_64-linux-gnu/libQt5Core.so.5(_ZN7QObject5eventEP6QEvent+0x280)[0x7fa5e6e512d0]
/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(_ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent+0x7e)[0x7fa5e7b2901e]
/usr/lib/x86_64-linux-gnu/libQt5Core.so.5(_ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent+0x118)[0x7fa5e6e25178]
/usr/lib/x86_64-linux-gnu/libQt5Core.so.5(_ZN23QCoreApplicationPrivate16sendPostedEventsEP7QObjectiP11QThreadData+0x191)[0x7fa5e6e28111]
/usr/lib/x86_64-linux-gnu/libQt5Core.so.5(+0x326df3)[0x7fa5e6e7ddf3]
/usr/lib/x86_64-linux-gnu/libglib-2.0.so.0(g_main_context_dispatch+0x2a1)[0x7fa5e80e2d71]
/usr/lib/x86_64-linux-gnu/libglib-2.0.so.0(+0xb0028)[0x7fa5e8139028]
/usr/lib/x86_64-linux-gnu/libglib-2.0.so.0(g_main_context_iteration+0x33)[0x7fa5e80e04a3]
/usr/lib/x86_64-linux-gnu/libQt5Core.so.5(_ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE+0x66)[0x7fa5e6e7d4d6]
/usr/lib/x86_64-linux-gnu/libQt5Core.so.5(_ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE+0x12b)[0x7fa5e6e23beb]
/usr/lib/x86_64-linux-gnu/libQt5Core.so.5(_ZN16QCoreApplication4execEv+0x96)[0x7fa5e6e2bd56]
io.github.NhekoReborn.Nheko(main+0xffc)[0x55eaf50accfc]
/usr/lib/x86_64-linux-gnu/libc.so.6(+0x2954a)[0x7fa5e647354a]
/usr/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x8b)[0x7fa5e647360b]
io.github.NhekoReborn.Nheko(+0x18fe05)[0x55eaf50ade05]
```

### To Reproduce

1. Write a message (it sould not been delivered)
2. try to edit it

### What happened?

Segfault catched on message edit

### Version

0.11.3-d27e42d

### Operating system

Linux

### Installation method

Flathub

### Desktop Environment

i3 with MATE

### Did you use profiles?

- [X] Profiles used?

**Comment by deepbluev7** [comment]
Can you install the debug symbols for Nheko?

**Comment by pizdjuk** [comment]
> Can you install the debug symbols for Nheko and reproduce the crash?

Here is backtrace from gdb
```
#0  0x00007ffff50e1184 in __pthread_kill_implementation () at /usr/lib/x86_64-linux-gnu/libc.so.6
#1  0x00007ffff508f00e in raise () at /usr/lib/x86_64-linux-gnu/libc.so.6
#2  0x00007ffff50787fc in abort () at /usr/lib/x86_64-linux-gnu/libc.so.6
#3  0x00007ffff5444f9d in  () at /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00005555557b28c2 in std::_Optional_base_impl<int, std::_Optional_base<int, true, true> >::_M_get() (this=0x7fffffffbcd0) at /usr/include/c++/12.2.0/optional:477
#5  std::optional<int>::operator*() & (this=0x7fffffffbcd0) at /usr/include/c++/12.2.0/optional:974
#6  operator()(std::string, std::string) constPython Exception <class 'gdb.error'>: value has been optimized out
Python Exception <class 'gdb.error'>: value has been optimized out
 (__closure=<optimized out>, txn_id=, event_id=) at /run/build/nheko/src/timeline/EventStore.cpp:269
#7  0x00005555557b2a84 in QtPrivate::FunctorCall<QtPrivate::IndexesList<0, 1>, QtPrivate::List<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, void, EventStore::EventStore(std::string, QObject*)::<lambda(std::string, std::string)> >::call (arg=<optimized out>, f=...) at /usr/include/QtCore/qobjectdefs_impl.h:146
#8  QtPrivate::Functor<EventStore::EventStore(std::string, QObject*)::<lambda(std::string, std::string)>, 2>::call<QtPrivate::List<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, void> (arg=<optimized out>, f=...) at /usr/include/QtCore/qobjectdefs_impl.h:256
#9  QtPrivate::QFunctorSlotObject<EventStore::EventStore(std::string, QObject*)::<lambda(std::string, std::string)>, 2, QtPrivate::List<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, void>::impl(int, QtPrivate::QSlotObjectBase *, QObject *, void **, bool *)
    (which=<optimized out>, this_=0x5555584d34d0, r=<optimized out>, a=<optimized out>, ret=<optimized out>) at /usr/include/QtCore/qobjectdefs_impl.h:443
#10 0x00007ffff5a572d0 in QObject::event(QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#11 0x00007ffff672f01e in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#12 0x00007ffff5a2b178 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#13 0x00007ffff5a2e111 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#14 0x00007ffff5a83df3 in  () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#15 0x00007ffff6ce8d71 in g_main_context_dispatch () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#16 0x00007ffff6d3f028 in g_main_context_iterate.constprop () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#17 0x00007ffff6ce64a3 in g_main_context_iteration () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#18 0x00007ffff5a834d6 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#19 0x00007ffff5a29beb in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#20 0x00007ffff5a31d56 in QCoreApplication::exec() () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#21 0x00005555556e2cfc in main(int, char**) (argc=<optimized out>, argv=<optimized out>) at /run/build/nheko/src/main.cpp:405
(gdb)                                                                                                                                                
```

**Comment by deepbluev7** [comment]
Thanks, that should fix it :)
