### ISSUE TITLE
Nheko freezes up and crashes when I type something specific

### ISSUE THREAD

**Issue by Starcr0ss** [Nheko-Reborn/nheko#1486]
### Describe the bug

If you type `:) ( <backspace> )`, it seems that the emoji suggestion popup has an issue, locks up the app, and triggers my KDE Plasma to ask if I want to terminate nheko. Also, I hear my fans on my computer start to rev when the app locks up.

### To Reproduce

1. Type in `:)`
2. Type a `(`
3. Backspace and try to type a `)`
4. App freezes and needs to be killed

### Expected behavior

The app should not crash when typing in characters in this order

### Version

0.11.3

### Operating system

Linux

### Installation method

Some repository (AUR, homebrew, distribution repository, PPA, etc)

### Qt version

5.15.9

### Desktop Environment

KDE Plasma 5.27.5 (just has KWin)

### Did you use profiles?

- [ ] Profiles used?

### Relevant log output

```shell
[2023-06-11 18:11:51.122] [net] [error] sync error: (connection: Operation was aborted by an application callback, parser: [json.exception.parse_error.101] parse error at line 1, column 1: syntax error while parsing value - unexpected end of input; expected '[', '{', or a literal [while parsing error]: )
[2023-06-11 18:11:51.166] [qml] [warning] Please call QDesktopServices::unsetUrlHandler() before destroying a registered URL handler object.
Support for destroying a registered URL handler object is deprecated, and will be removed in Qt 6.6. (:0, )
```

**Comment by heylix** [comment]
Same here, but it also happens when I write stuff like `shall we meet at 07:00 UTC or 09:00 UTC?`. I guess it tries to interpret the stuff between the colons as emojis and the search kills it.

Of course when I did `strace nheko`, the error doesn't appear immediately. Looks like we got a genuine Heisenbug on our hands! :grinning:

**Comment by jktjkt** [comment]
this just happened to me (nheko 0.11.3) when I typed backtick - colon - y. Here's the backtrace:
```
(gdb) bt
#0  0x00007f2a2b0afb58 in QV4::MarkStack::drain() () from /nix/store/kwq59ygf83qbakhxjhkdh4whsbjah6d8-qtdeclarative-5.15.9/lib/libQt5Qml.so.5
#1  0x00007f2a2b133fd0 in QV4::PersistentValueStorage::mark(QV4::MarkStack*) () from /nix/store/kwq59ygf83qbakhxjhkdh4whsbjah6d8-qtdeclarative-5.15.9/lib/libQt5Qml.so.5
#2  0x00007f2a2b0b01ed in QV4::MemoryManager::collectRoots(QV4::MarkStack*) () from /nix/store/kwq59ygf83qbakhxjhkdh4whsbjah6d8-qtdeclarative-5.15.9/lib/libQt5Qml.so.5
#3  0x00007f2a2b0b044c in QV4::MemoryManager::mark() () from /nix/store/kwq59ygf83qbakhxjhkdh4whsbjah6d8-qtdeclarative-5.15.9/lib/libQt5Qml.so.5
#4  0x00007f2a2b0b2160 in QV4::MemoryManager::runGC() [clone .part.0] () from /nix/store/kwq59ygf83qbakhxjhkdh4whsbjah6d8-qtdeclarative-5.15.9/lib/libQt5Qml.so.5
#5  0x00007f2a2b0b4596 in QV4::MemoryManager::allocString(unsigned long) () from /nix/store/kwq59ygf83qbakhxjhkdh4whsbjah6d8-qtdeclarative-5.15.9/lib/libQt5Qml.so.5
#6  0x00007f2a2b11c0ed in QV4::ExecutionEngine::newString(QString const&) () from /nix/store/kwq59ygf83qbakhxjhkdh4whsbjah6d8-qtdeclarative-5.15.9/lib/libQt5Qml.so.5
#7  0x00007f2a2b15ae33 in QV4::ErrorPrototype::method_toString(QV4::FunctionObject const*, QV4::Value const*, QV4::Value const*, int) ()
   from /nix/store/kwq59ygf83qbakhxjhkdh4whsbjah6d8-qtdeclarative-5.15.9/lib/libQt5Qml.so.5
#8  0x00007f2a2b1dcf9f in QV4::RuntimeHelpers::ordinaryToPrimitive(QV4::ExecutionEngine*, QV4::Object const*, QV4::String*) ()
   from /nix/store/kwq59ygf83qbakhxjhkdh4whsbjah6d8-qtdeclarative-5.15.9/lib/libQt5Qml.so.5
#9  0x00007f2a2b1dd314 in QV4::RuntimeHelpers::objectDefaultValue(QV4::Object const*, int) () from /nix/store/kwq59ygf83qbakhxjhkdh4whsbjah6d8-qtdeclarative-5.15.9/lib/libQt5Qml.so.5
#10 0x00007f2a2b1e244e in QV4::Value::toQStringNoThrow() const () from /nix/store/kwq59ygf83qbakhxjhkdh4whsbjah6d8-qtdeclarative-5.15.9/lib/libQt5Qml.so.5
#11 0x00007f2a2b12634e in QV4::ExecutionEngine::catchExceptionAsQmlError() () from /nix/store/kwq59ygf83qbakhxjhkdh4whsbjah6d8-qtdeclarative-5.15.9/lib/libQt5Qml.so.5
#12 0x00007f2a2b2e6b16 in QQmlJavaScriptExpression::evaluate(QV4::CallData*, bool*) () from /nix/store/kwq59ygf83qbakhxjhkdh4whsbjah6d8-qtdeclarative-5.15.9/lib/libQt5Qml.so.5
#13 0x00007f2a2b2eccdb in QQmlBinding::evaluate(bool*) () from /nix/store/kwq59ygf83qbakhxjhkdh4whsbjah6d8-qtdeclarative-5.15.9/lib/libQt5Qml.so.5
#14 0x00007f2a2b2f0f83 in QQmlNonbindingBinding::doUpdate(QQmlJavaScriptExpression::DeleteWatcher const&, QFlags<QQmlPropertyData::WriteFlag>, QV4::Scope&) ()
   from /nix/store/kwq59ygf83qbakhxjhkdh4whsbjah6d8-qtdeclarative-5.15.9/lib/libQt5Qml.so.5
#15 0x00007f2a2b2eeac4 in QQmlBinding::update(QFlags<QQmlPropertyData::WriteFlag>) () from /nix/store/kwq59ygf83qbakhxjhkdh4whsbjah6d8-qtdeclarative-5.15.9/lib/libQt5Qml.so.5
#16 0x00007f2a2b2fbef2 in QQmlObjectCreator::finalize(QQmlInstantiationInterrupt&) () from /nix/store/kwq59ygf83qbakhxjhkdh4whsbjah6d8-qtdeclarative-5.15.9/lib/libQt5Qml.so.5
#17 0x00007f2a2b291ec2 in QQmlIncubatorPrivate::incubate(QQmlInstantiationInterrupt&) () from /nix/store/kwq59ygf83qbakhxjhkdh4whsbjah6d8-qtdeclarative-5.15.9/lib/libQt5Qml.so.5
#18 0x00007f2a2b29235d in QQmlEnginePrivate::incubate(QQmlIncubator&, QQmlContextData*) () from /nix/store/kwq59ygf83qbakhxjhkdh4whsbjah6d8-qtdeclarative-5.15.9/lib/libQt5Qml.so.5
#19 0x00007f2a2c1e7a30 in QQmlDelegateModelPrivate::object(QQmlListCompositor::Group, int, QQmlIncubator::IncubationMode) ()
   from /nix/store/kwq59ygf83qbakhxjhkdh4whsbjah6d8-qtdeclarative-5.15.9/lib/libQt5QmlModels.so.5
#20 0x00007f2a2b91f463 in QQuickItemViewPrivate::createItem(int, QQmlIncubator::IncubationMode) ()
   from /nix/store/kwq59ygf83qbakhxjhkdh4whsbjah6d8-qtdeclarative-5.15.9/lib/libQt5Quick.so.5
#21 0x00007f2a2b92f380 in QQuickListViewPrivate::addVisibleItems(double, double, double, double, bool) ()
   from /nix/store/kwq59ygf83qbakhxjhkdh4whsbjah6d8-qtdeclarative-5.15.9/lib/libQt5Quick.so.5
#22 0x00007f2a2b92043b in QQuickItemViewPrivate::refill(double, double) () from /nix/store/kwq59ygf83qbakhxjhkdh4whsbjah6d8-qtdeclarative-5.15.9/lib/libQt5Quick.so.5
#23 0x00007f2a2b9370d1 in QQuickListView::viewportMoved(QFlags<Qt::Orientation>) () from /nix/store/kwq59ygf83qbakhxjhkdh4whsbjah6d8-qtdeclarative-5.15.9/lib/libQt5Quick.so.5
#24 0x00007f2a2b8d031f in QQuickFlickablePrivate::itemGeometryChanged(QQuickItem*, QQuickGeometryChange, QRectF const&) ()
   from /nix/store/kwq59ygf83qbakhxjhkdh4whsbjah6d8-qtdeclarative-5.15.9/lib/libQt5Quick.so.5
#25 0x00007f2a2b91db89 in QQuickItemViewPrivate::itemGeometryChanged(QQuickItem*, QQuickGeometryChange, QRectF const&) ()
   from /nix/store/kwq59ygf83qbakhxjhkdh4whsbjah6d8-qtdeclarative-5.15.9/lib/libQt5Quick.so.5
#26 0x00007f2a2b934762 in QQuickListViewPrivate::itemGeometryChanged(QQuickItem*, QQuickGeometryChange, QRectF const&) ()
   from /nix/store/kwq59ygf83qbakhxjhkdh4whsbjah6d8-qtdeclarative-5.15.9/lib/libQt5Quick.so.5
#27 0x00007f2a2b857d03 in QQuickItem::geometryChanged(QRectF const&, QRectF const&) () from /nix/store/kwq59ygf83qbakhxjhkdh4whsbjah6d8-qtdeclarative-5.15.9/lib/libQt5Quick.so.5
#28 0x00007f2a2b855870 in QQuickItem::setY(double) () from /nix/store/kwq59ygf83qbakhxjhkdh4whsbjah6d8-qtdeclarative-5.15.9/lib/libQt5Quick.so.5
#29 0x00007f2a2b8d0b39 in QQuickFlickablePrivate::setViewportY(double) () from /nix/store/kwq59ygf83qbakhxjhkdh4whsbjah6d8-qtdeclarative-5.15.9/lib/libQt5Quick.so.5
#30 0x00007f2a2b757642 in QQuickTimeLinePrivate::advance(int) () from /nix/store/kwq59ygf83qbakhxjhkdh4whsbjah6d8-qtdeclarative-5.15.9/lib/libQt5Quick.so.5
#31 0x00007f2a2b757939 in QQuickTimeLine::updateCurrentTime(int) () from /nix/store/kwq59ygf83qbakhxjhkdh4whsbjah6d8-qtdeclarative-5.15.9/lib/libQt5Quick.so.5
#32 0x00007f2a2b344c9d in QAbstractAnimationJob::setCurrentTime(int) () from /nix/store/kwq59ygf83qbakhxjhkdh4whsbjah6d8-qtdeclarative-5.15.9/lib/libQt5Qml.so.5
#33 0x00007f2a2b344841 in QAbstractAnimationJob::setState(QAbstractAnimationJob::State) () from /nix/store/kwq59ygf83qbakhxjhkdh4whsbjah6d8-qtdeclarative-5.15.9/lib/libQt5Qml.so.5
#34 0x00007f2a2b7567da in QQuickTimeLine::set(QQuickTimeLineValue&, double) () from /nix/store/kwq59ygf83qbakhxjhkdh4whsbjah6d8-qtdeclarative-5.15.9/lib/libQt5Quick.so.5
#35 0x00007f2a2b8d9b1e in QQuickFlickablePrivate::fixup(QQuickFlickablePrivate::AxisData&, double, double) ()
   from /nix/store/kwq59ygf83qbakhxjhkdh4whsbjah6d8-qtdeclarative-5.15.9/lib/libQt5Quick.so.5
#36 0x00007f2a2b934eef in QQuickListViewPrivate::fixup(QQuickFlickablePrivate::AxisData&, double, double) ()
   from /nix/store/kwq59ygf83qbakhxjhkdh4whsbjah6d8-qtdeclarative-5.15.9/lib/libQt5Quick.so.5
#37 0x00007f2a2b92172f in QQuickItemViewPrivate::layout() () from /nix/store/kwq59ygf83qbakhxjhkdh4whsbjah6d8-qtdeclarative-5.15.9/lib/libQt5Quick.so.5
#38 0x00007f2a2b873ea2 in QQuickWindowPrivate::polishItems() () from /nix/store/kwq59ygf83qbakhxjhkdh4whsbjah6d8-qtdeclarative-5.15.9/lib/libQt5Quick.so.5
#39 0x00007f2a2b81555d in QSGThreadedRenderLoop::polishAndSync(QSGThreadedRenderLoop::Window*, bool) ()
   from /nix/store/kwq59ygf83qbakhxjhkdh4whsbjah6d8-qtdeclarative-5.15.9/lib/libQt5Quick.so.5
#40 0x00007f2a2b8811f0 in QQuickWindow::event(QEvent*) () from /nix/store/kwq59ygf83qbakhxjhkdh4whsbjah6d8-qtdeclarative-5.15.9/lib/libQt5Quick.so.5
#41 0x00007f2a2a97105e in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /nix/store/rxrqwndv5xab8jdb0yxh3arf3jp6yn50-qtbase-5.15.9/lib/libQt5Widgets.so.5
#42 0x00007f2a29aca878 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /nix/store/rxrqwndv5xab8jdb0yxh3arf3jp6yn50-qtbase-5.15.9/lib/libQt5Core.so.5
#43 0x00007f2a2a11e878 in QPlatformWindow::deliverUpdateRequest() () from /nix/store/rxrqwndv5xab8jdb0yxh3arf3jp6yn50-qtbase-5.15.9/lib/libQt5Gui.so.5
#44 0x00007f2a29af68f0 in QObject::event(QEvent*) () from /nix/store/rxrqwndv5xab8jdb0yxh3arf3jp6yn50-qtbase-5.15.9/lib/libQt5Core.so.5
#45 0x00007f2a2a97105e in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /nix/store/rxrqwndv5xab8jdb0yxh3arf3jp6yn50-qtbase-5.15.9/lib/libQt5Widgets.so.5
#46 0x00007f2a29aca878 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /nix/store/rxrqwndv5xab8jdb0yxh3arf3jp6yn50-qtbase-5.15.9/lib/libQt5Core.so.5
#47 0x00007f2a29acd8b1 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () from /nix/store/rxrqwndv5xab8jdb0yxh3arf3jp6yn50-qtbase-5.15.9/lib/libQt5Core.so.5
#48 0x00007f2a29b23273 in postEventSourceDispatch(_GSource*, int (*)(void*), void*) () from /nix/store/rxrqwndv5xab8jdb0yxh3arf3jp6yn50-qtbase-5.15.9/lib/libQt5Core.so.5
#49 0x00007f2a2a715dfd in g_main_context_dispatch () from /nix/store/1635p7fbsqrqf6k5p449pwnp81y6hxlf-glib-2.76.3/lib/libglib-2.0.so.0
#50 0x00007f2a2a7160a8 in g_main_context_iterate.constprop () from /nix/store/1635p7fbsqrqf6k5p449pwnp81y6hxlf-glib-2.76.3/lib/libglib-2.0.so.0
#51 0x00007f2a2a71613c in g_main_context_iteration () from /nix/store/1635p7fbsqrqf6k5p449pwnp81y6hxlf-glib-2.76.3/lib/libglib-2.0.so.0
#52 0x00007f2a29b22a56 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /nix/store/rxrqwndv5xab8jdb0yxh3arf3jp6yn50-qtbase-5.15.9/lib/libQt5Core.so.5
#53 0x00007f2a29ac9273 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /nix/store/rxrqwndv5xab8jdb0yxh3arf3jp6yn50-qtbase-5.15.9/lib/libQt5Core.so.5
#54 0x00007f2a29ad1776 in QCoreApplication::exec() () from /nix/store/rxrqwndv5xab8jdb0yxh3arf3jp6yn50-qtbase-5.15.9/lib/libQt5Core.so.5
#55 0x00000000005698e5 in main ()
```

**Comment by mageOfstructs** [comment]
is not reproducible now, so maybe this was solved?
