### ISSUE TITLE
[qt6] Crash when re-entering a room where a video was played

### ISSUE THREAD

**Issue by TheSunCat** [Nheko-Reborn/nheko#1525]
### Describe the bug

nheko crashes when the steps are followed

### To Reproduce

1. Open a room with a video
2. Start watching the video within nheko
3. Two options:
  a. Close the room and reopen it.
  b. Go to another room, then another, then a third.
7. Observe the crash

### What happened?

nheko froze and crashed a second later

### Expected behavior

nheko should not crash

### Version

0.11.3-4bd6aeab

### Operating system

Linux

### Installation method

Some repository (AUR, homebrew, distribution repository, PPA, etc)

### Desktop Environment

Hyprland (Wayland)

### Did you use profiles?

- [ ] Profiles used?

### Relevant log output

```shell
[2023-07-14 00:02:34.677] [qml] [warning] qrc:/resources/qml/TimelineRow.qml:201:13: QML MessageDelegate: Binding loop detected for property "implicitWidth" (qrc:/resources/qml/TimelineRow.qml:201, )
[2023-07-14 00:02:34.684] [qml] [warning] qrc:/resources/qml/TimelineRow.qml:201:13: QML MessageDelegate: Binding loop detected for property "implicitWidth" (qrc:/resources/qml/TimelineRow.qml:201, )
[2023-07-14 00:02:34.695] [qml] [critical] Cannot make QOpenGLContext current in a different thread (:0, )
Error: signal 6:
nheko(+0x69aabd)[0x555a598f7abd]
/usr/lib/libc.so.6(+0x39ab0)[0x7f4d90b62ab0]
/usr/lib/libc.so.6(+0x8926c)[0x7f4d90bb226c]
/usr/lib/libc.so.6(gsignal+0x18)[0x7f4d90b62a08]
/usr/lib/libc.so.6(abort+0xd7)[0x7f4d90b4b538]
/usr/lib/libQt6Core.so.6(_Z9qt_assertPKcS0_i+0x0)[0x7f4d914a80da]
/usr/lib/libQt6Gui.so.6(+0x114c59)[0x7f4d91b14c59]
/usr/lib/libQt6Gui.so.6(+0x64d72a)[0x7f4d9204d72a]
/usr/lib/qt6/plugins/multimedia/libffmpegmediaplugin.so(+0x56fd3)[0x7f4d6c591fd3]
/usr/lib/qt6/plugins/multimedia/libffmpegmediaplugin.so(+0x2e95a)[0x7f4d6c56995a]
/usr/lib/qt6/plugins/multimedia/libffmpegmediaplugin.so(+0x2e97d)[0x7f4d6c56997d]
/usr/lib/libQt6Multimedia.so.6(_ZN11QVideoFrameD1Ev+0x2a)[0x7f4d9399c33a]
/usr/lib/libQt6Multimedia.so.6(_ZN18QPlatformVideoSinkD1Ev+0x1c)[0x7f4d9397adfc]
/usr/lib/qt6/plugins/multimedia/libffmpegmediaplugin.so(+0x29e7f)[0x7f4d6c564e7f]
/usr/lib/libQt6Multimedia.so.6(_ZN10QVideoSinkD1Ev+0x6e)[0x7f4d9399ec9e]
/usr/lib/libQt6Multimedia.so.6(_ZN10QVideoSinkD0Ev+0xd)[0x7f4d9399ecfd]
/usr/lib/libQt6Core.so.6(_ZN14QObjectPrivate14deleteChildrenEv+0x8b)[0x7f4d9157d81b]
/usr/lib/libQt6Core.so.6(_ZN7QObjectD1Ev+0x3b8)[0x7f4d91581018]
/usr/lib/qt6/qml/QtMultimedia/../../../libQt6MultimediaQuick.so.6(+0x1f2ea)[0x7f4d28ed82ea]
/usr/lib/libQt6Core.so.6(_ZN14QObjectPrivate14deleteChildrenEv+0x8b)[0x7f4d9157d81b]
/usr/lib/libQt6Core.so.6(_ZN7QObjectD1Ev+0x3b8)[0x7f4d91581018]
/usr/lib/libQt6Quick.so.6(+0x3cda1a)[0x7f4d935cda1a]
/usr/lib/libQt6Core.so.6(_ZN14QObjectPrivate14deleteChildrenEv+0x8b)[0x7f4d9157d81b]
/usr/lib/libQt6Core.so.6(_ZN7QObjectD1Ev+0x3b8)[0x7f4d91581018]
/usr/lib/libQt6Quick.so.6(+0x3cb6be)[0x7f4d935cb6be]
/usr/lib/libQt6Core.so.6(_ZN14QObjectPrivate14deleteChildrenEv+0x8b)[0x7f4d9157d81b]
/usr/lib/libQt6Core.so.6(_ZN7QObjectD1Ev+0x3b8)[0x7f4d91581018]
/usr/lib/libQt6Quick.so.6(+0x3cbc2a)[0x7f4d935cbc2a]
/usr/lib/libQt6Core.so.6(_ZN7QObject5eventEP6QEvent+0x58)[0x7f4d9157d1d8]
/usr/lib/libQt6Widgets.so.6(_ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent+0x4b)[0x7f4d9257145b]
/usr/lib/libQt6Core.so.6(_ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent+0x1d8)[0x7f4d9153aad8]
/usr/lib/libQt6Core.so.6(_ZN23QCoreApplicationPrivate16sendPostedEventsEP7QObjectiP11QThreadData+0x32b)[0x7f4d9153ae5b]
/usr/lib/libQt6Core.so.6(+0x336624)[0x7f4d91736624]
/usr/lib/libglib-2.0.so.0(g_main_context_dispatch+0x141)[0x7f4d911b8a31]
/usr/lib/libglib-2.0.so.0(+0xb7cc9)[0x7f4d91215cc9]
/usr/lib/libglib-2.0.so.0(g_main_context_iteration+0x32)[0x7f4d911b60e2]
/usr/lib/libQt6Core.so.6(_ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE+0x84)[0x7f4d917344d4]
/usr/lib/libQt6Core.so.6(_ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE+0x1a3)[0x7f4d91544cd3]
/usr/lib/libQt6Core.so.6(_ZN16QCoreApplication4execEv+0x88)[0x7f4d9153e378]
nheko(main+0x1784)[0x555a5942eb64]
/usr/lib/libc.so.6(+0x23850)[0x7f4d90b4c850]
/usr/lib/libc.so.6(__libc_start_main+0x8a)[0x7f4d90b4c90a]
nheko(+0x1d42d5)[0x555a594312d5]
zsh: IOT instruction (core dumped)  nheko
```

### Backtrace

```shell
[2023-07-14 00:03:04.521] [qml] [warning] qrc:/resources/qml/TimelineRow.qml:201:13: QML MessageDelegate: Binding loop detected for property "implicitWidth" (qrc:/resources/qml/TimelineRow.qml:201, )
[New Thread 0x7ff6c2de96c0 (LWP 668902)]
[Thread 0x7ff6d8ff16c0 (LWP 668553) exited]
[Thread 0x7ff6d97f26c0 (LWP 668552) exited]
[Thread 0x7ff6d9ff36c0 (LWP 668551) exited]
[Thread 0x7ff6daff56c0 (LWP 668549) exited]
[Thread 0x7ff6da7f46c0 (LWP 668550) exited]
[Thread 0x7ff6eb7fe6c0 (LWP 668533) exited]
[Thread 0x7ff6eaffd6c0 (LWP 668534) exited]
[Thread 0x7ff6ea7fc6c0 (LWP 668535) exited]
[Thread 0x7ff6e9ffb6c0 (LWP 668536) exited]
[Thread 0x7ff6e97fa6c0 (LWP 668537) exited]
[Thread 0x7ff6e8ff96c0 (LWP 668538) exited]
[Thread 0x7ff6dffff6c0 (LWP 668539) exited]
[Thread 0x7ff6df7fe6c0 (LWP 668540) exited]
[Thread 0x7ff6deffd6c0 (LWP 668541) exited]
[Thread 0x7ff6de7fc6c0 (LWP 668542) exited]
[Thread 0x7ff6ddffb6c0 (LWP 668543) exited]
[Thread 0x7ff6dd7fa6c0 (LWP 668544) exited]
[Thread 0x7ff6dcff96c0 (LWP 668545) exited]
[Thread 0x7ff6dc7f86c0 (LWP 668546) exited]
[Thread 0x7ff6dbff76c0 (LWP 668547) exited]
[Thread 0x7ff6db7f66c0 (LWP 668548) exited]
[2023-07-14 00:03:04.545] [qml] [critical] Cannot make QOpenGLContext current in a different thread (:0, )

Thread 1 "nheko" received signal SIGABRT, Aborted.
0x00007ffff49b226c in ?? () from /usr/lib/libc.so.6
(gdb) bt
#0  0x00007ffff49b226c in  () at /usr/lib/libc.so.6
#1  0x00007ffff4962a08 in raise () at /usr/lib/libc.so.6
#2  0x00007ffff494b538 in abort () at /usr/lib/libc.so.6
#3  0x00007ffff52a80da in qt_assert(char const*, char const*, int) () at /usr/lib/libQt6Core.so.6
#4  0x00007ffff5914c59 in  () at /usr/lib/libQt6Gui.so.6
#5  0x00007ffff5e4d72a in  () at /usr/lib/libQt6Gui.so.6
#6  0x00007fffb4a81fd3 in  () at /usr/lib/qt6/plugins/multimedia/libffmpegmediaplugin.so
#7  0x00007fffb4a5995a in  () at /usr/lib/qt6/plugins/multimedia/libffmpegmediaplugin.so
#8  0x00007fffb4a5997d in  () at /usr/lib/qt6/plugins/multimedia/libffmpegmediaplugin.so
#9  0x00007ffff773d33a in QVideoFrame::~QVideoFrame() () at /usr/lib/libQt6Multimedia.so.6
#10 0x00007ffff771bdfc in QPlatformVideoSink::~QPlatformVideoSink() () at /usr/lib/libQt6Multimedia.so.6
#11 0x00007fffb4a54e7f in  () at /usr/lib/qt6/plugins/multimedia/libffmpegmediaplugin.so
#12 0x00007ffff773fc9e in QVideoSink::~QVideoSink() () at /usr/lib/libQt6Multimedia.so.6
#13 0x00007ffff773fcfd in QVideoSink::~QVideoSink() () at /usr/lib/libQt6Multimedia.so.6
#14 0x00007ffff537d81b in QObjectPrivate::deleteChildren() () at /usr/lib/libQt6Core.so.6
#15 0x00007ffff5381018 in QObject::~QObject() () at /usr/lib/libQt6Core.so.6
#16 0x00007fff8dca42ea in  () at /usr/lib/qt6/qml/QtMultimedia/../../../libQt6MultimediaQuick.so.6
#17 0x00007ffff537d81b in QObjectPrivate::deleteChildren() () at /usr/lib/libQt6Core.so.6
#18 0x00007ffff5381018 in QObject::~QObject() () at /usr/lib/libQt6Core.so.6
#19 0x00007ffff73cda1a in  () at /usr/lib/libQt6Quick.so.6
#20 0x00007ffff537d81b in QObjectPrivate::deleteChildren() () at /usr/lib/libQt6Core.so.6
#21 0x00007ffff5381018 in QObject::~QObject() () at /usr/lib/libQt6Core.so.6
#22 0x00007ffff73cb6be in  () at /usr/lib/libQt6Quick.so.6
#23 0x00007ffff537d81b in QObjectPrivate::deleteChildren() () at /usr/lib/libQt6Core.so.6
#24 0x00007ffff5381018 in QObject::~QObject() () at /usr/lib/libQt6Core.so.6
#25 0x00007ffff73cbc2a in  () at /usr/lib/libQt6Quick.so.6
#26 0x00007ffff537d1d8 in QObject::event(QEvent*) () at /usr/lib/libQt6Core.so.6
#27 0x00007ffff637145b in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/libQt6Widgets.so.6
#28 0x00007ffff533aad8 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/libQt6Core.so.6
#29 0x00007ffff533ae5b in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () at /usr/lib/libQt6Core.so.6
#30 0x00007ffff5536624 in  () at /usr/lib/libQt6Core.so.6
#31 0x00007ffff4fb8a31 in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
#32 0x00007ffff5015cc9 in  () at /usr/lib/libglib-2.0.so.0
#33 0x00007ffff4fb60e2 in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#34 0x00007ffff55344d4 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt6Core.so.6
#35 0x00007ffff5344cd3 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt6Core.so.6
#36 0x00007ffff533e378 in QCoreApplication::exec() () at /usr/lib/libQt6Core.so.6
#37 0x0000555555725b64 in main ()
```

**Comment by deepbluev7** [comment]
Should be fixed now.
