### ISSUE TITLE
Nheko doesn't open in antergos (qt5ct issues?)

### ISSUE THREAD

**Issue by qazip** [Nheko-Reborn/nheko#53]
### System:

- Nheko version: I have the nheko version from aur. 
- Installation method: AUR
- Operating System: Antergos
- Desktop Environment: i3wm

Ever since I made some updates, nheko stopped working. Here is the output of "nheko:":

```
nheko
qt5ct: using qt5ct plugin

(nheko:16326): Gtk-WARNING **: 14:36:45.686: Unable to locate theme engine in module_path: "adwaita",

(nheko:16326): Gtk-WARNING **: 14:36:45.688: Unable to locate theme engine in module_path: "adwaita",
qt5ct: D-Bus system tray: no
qt5ct: custom style sheet is disabled
[1]    16326 abort (core dumped)  nheko
```

**Comment by redsky17** [comment]
Could you try running nheko with gdb and getting a stack trace, so I can see where it's crashing?

**Comment by qazip** [comment]
Can you point me to the right direction on how to do that? `gdb nheko` opens a console. In that console, doing `run nheko` doesn't work.

**Comment by qazip** [comment]
Ignore my previous post. Here it is:

```
(gdb) run nheko 
Starting program: /usr/bin/nheko nheko
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[New Thread 0x7ffff2402700 (LWP 13193)]
[New Thread 0x7ffff1c01700 (LWP 13194)]
[New Thread 0x7ffff1400700 (LWP 13195)]
[New Thread 0x7ffff0bff700 (LWP 13196)]
[New Thread 0x7fffef1da700 (LWP 13197)]
qt5ct: using qt5ct plugin

(nheko:13189): Gtk-WARNING **: 12:37:39.803: Unable to locate theme engine in module_path: "adwaita",

(nheko:13189): Gtk-WARNING **: 12:37:39.804: Unable to locate theme engine in module_path: "adwaita",
[New Thread 0x7fffe7fff700 (LWP 13198)]
qt5ct: D-Bus system tray: no
qt5ct: custom style sheet is disabled

Thread 1 "nheko" received signal SIGSEGV, Segmentation fault.
0x0000555555624454 in std::_Sp_counted_ptr_inplace<mtx::http::Session, std::allocator<mtx::http::Session>, (__gnu_cxx::_Lock_policy)2>::_M_get_deleter(std::type_info const&)
    ()
```

**Comment by redsky17** [comment]
After you get nheko to crash in gdb, can you run 'bt' so I can see the full
stack trace?

**Comment by qazip** [comment]
@redsky17, here it is:

```
(gdb) bt
#0  0x0000555555624454 in std::_Sp_counted_ptr_inplace<mtx::http::Session, std::allocator<mtx::http::Session>, (__gnu_cxx::_Lock_policy)2>::_M_get_deleter(std::type_info const&) ()
#1  0x00007ffff7e1900f in std::shared_ptr<mtx::http::Session> mtx::http::Client::create_session<mtx::responses::GroupProfile>(std::function<void (mtx::responses::GroupProfile const&, boost::optional<boost::beast::http::basic_fields<std::allocator<char> > > const&, boost::optional<mtx::http::ClientError> const&)>) ()
    at /usr/lib/libmatrix_client.so.0.2.0
#2  0x00007ffff7e1e662 in void mtx::http::Client::get<mtx::responses::GroupProfile>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::function<void (mtx::responses::GroupProfile const&, boost::optional<boost::beast::http::basic_fields<std::allocator<char> > > const&, boost::optional<mtx::http::ClientError> const&)>, bool) () at /usr/lib/libmatrix_client.so.0.2.0
#3  0x00007ffff7dc6317 in mtx::http::Client::group_profile(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::function<void (mtx::responses::GroupProfile const&, boost::optional<mtx::http::ClientError> const&)>) () at /usr/lib/libmatrix_client.so.0.2.0
#4  0x00005555557185e0 in  ()
#5  0x000055555571929a in  ()
#6  0x00005555557046e5 in  ()
#7  0x000055555572b85c in  ()
#8  0x00005555555fd72d in main ()
```

**Comment by qazip** [comment]
Was this helpful @redsky17? If you need something else, please let me know. I would love to be able to use nheko!

**Comment by redsky17** [comment]
Sorry, totally forgot to follow up on this after I read it the other day.  It appears that something is happening in mtxclient that's causing the core dump.  I'll have to investigate more to figure out the cause.

**Comment by redsky17** [comment]
Looks like the seg fault is happening during the creation of the shared pointer for the HTTP session that's fetching some group/community information.  I don't see anything obviously wrong with the code, so can you provide me more info?

Firstly, would you be able to run nheko with valgrind and provide the output to me?

Secondly, when you built it from the AUR repo, do you know which compiler it used?

**Comment by qazip** [comment]
This is no longer an issue, fomr some reason. Closing!
