### ISSUE TITLE
Launching Nheko for first time causes a crash

### ISSUE THREAD

**Issue by exaCORE42** [Nheko-Reborn/nheko#792]
### Describe the bug

When launching Nheko for the first time, it crashes.

### To Reproduce

1. Delete ~/.config/nheko/nheko.conf
2. Launch Nheko
3. See it crash

### What happened?

It crashes.  You can fix this by deleting the [auth] section of ~/.config/nheko/nheko.conf after it generates for the first time.  When this config file generates for the first time, the [auth] section has blank config options (maybe this is the source of the crash).  After you delete the section detailed previously, nheko will start and you can attempt to log in.

### Expected behavior

It would not crash on first launch.

### Version

The latest commit (I am unable to access the settings menu because I cannot log in due to a different bug

### Operating system

Linux

### Installation method

Some repository (AUR, homebrew, distribution repository, PPA, etc)

### Qt version

qt5-base 5.15.2+kde+r254-1

### C++ compiler

gcc 11.1.0

### Desktop Environment

KDE

### Did you use profiles?

- [ ] Profiles used?

### Relevant log output

```shell
[2021-11-07 14:08:16.753] [ui] [info] Restoring window size 0x0
[2021-11-07 14:08:16.809] [ui] [info] WebRTC: initialised GStreamer 1.18.5
[2021-11-07 14:08:17.019] [ui] [info] jdenticon plugin not found.
[2021-11-07 14:08:17.234] [ui] [debug] Profile requested
[2021-11-07 14:08:17.325] [ui] [debug] Status changed to 1
[2021-11-07 14:08:17.340] [ui] [debug] WebRTC: audio device added: Monitor of Built-in Audio Analog Stereo
[2021-11-07 14:08:17.342] [ui] [debug] WebRTC: audio device added: Built-in Audio Analog Stereo
[2021-11-07 14:08:17.343] [ui] [debug] WebRTC: video device added: Laptop_Integrated_Webcam_E4HD:
[2021-11-07 14:08:17.408] [ui] [info] starting nheko 0.8.2-1bdf4ebd
[2021-11-07 14:08:17.462] [db] [debug] setting up cache
[2021-11-07 14:08:17.462] [db] [info] Invalidating self verification status
[2021-11-07 14:08:17.462] [db] [error] Failed to retrieve user keys for : mdb_get: MDB_BAD_VALSIZE: Unsupported size of key/DB name/data, or wrong DUPFIXED size
/usr/include/c++/11.1.0/optional:440: constexpr _Tp& std::_Optional_base_impl<_Tp, _Dp>::_M_get() [with _Tp = UserKeyCache; _Dp = std::_Optional_base<UserKeyCache, false, false>]: Assertion 'this->_M_is_engaged()' failed.
Error: signal 6:
nheko(_Z17stacktraceHandleri+0x41)[0x5569e2700161]
/usr/lib/libc.so.6(+0x3cda0)[0x7f705c667da0]
/usr/lib/libc.so.6(gsignal+0x142)[0x7f705c667d22]
/usr/lib/libc.so.6(abort+0x116)[0x7f705c651862]
nheko(+0x30cb6a)[0x5569e242fb6a]
nheko(_ZN22SelfVerificationStatus10invalidateEv+0x688)[0x5569e25c7b48]
/usr/lib/libQt5Core.so.5(+0x2f07ab)[0x7f705d1bb7ab]
nheko(_ZN10MainWindow12showChatPageEv+0x9f0)[0x5569e26aaa80]
nheko(+0x588680)[0x5569e26ab680]
/usr/lib/libQt5Core.so.5(_ZN7QObject5eventEP6QEvent+0x2af)[0x7f705d1b154f]
/usr/lib/libQt5Widgets.so.5(_ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent+0x82)[0x7f705de01d62]
/usr/lib/libQt5Core.so.5(_ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent+0x13a)[0x7f705d1843fa]
/usr/lib/libQt5Core.so.5(_ZN23QCoreApplicationPrivate16sendPostedEventsEP7QObjectiP11QThreadData+0x189)[0x7f705d1874f9]
/usr/lib/libQt5Core.so.5(+0x3129f4)[0x7f705d1dd9f4]
/usr/lib/libglib-2.0.so.0(g_main_context_dispatch+0x26c)[0x7f705cc1c4dc]
/usr/lib/libglib-2.0.so.0(+0xa8799)[0x7f705cc70799]
/usr/lib/libglib-2.0.so.0(g_main_context_iteration+0x31)[0x7f705cc19bc1]
/usr/lib/libQt5Core.so.5(_ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE+0x66)[0x7f705d1dd026]
/usr/lib/libQt5Core.so.5(_ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE+0x12c)[0x7f705d182d6c]
/usr/lib/libQt5Core.so.5(_ZN16QCoreApplication4execEv+0x94)[0x7f705d18b2d4]
nheko(main+0xe13)[0x5569e24284c3]
/usr/lib/libc.so.6(__libc_start_main+0xd5)[0x7f705c652b25]
nheko(_start+0x2e)[0x5569e242988e]
Aborted (core dumped)
```

### Backtrace

```shell
#0  0x00007ffff518ed22 in raise () at /usr/lib/libc.so.6
#1  0x00007ffff5178862 in abort () at /usr/lib/libc.so.6
#2  0x0000555555860b6a in  ()
#3  0x00005555559f8b48 in SelfVerificationStatus::invalidate() ()
#4  0x00007ffff5ce27ab in  () at /usr/lib/libQt5Core.so.5
#5  0x0000555555adba80 in MainWindow::showChatPage() ()
#6  0x0000555555adc680 in  ()
#7  0x00007ffff5cd854f in QObject::event(QEvent*) () at /usr/lib/libQt5Core.so.5
#8  0x00007ffff6928d62 in QApplicationPrivate::notify_helper(QObject*, QEvent*) ()
    at /usr/lib/libQt5Widgets.so.5
#9  0x00007ffff5cab3fa in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/libQt5Core.so.5
#10 0x00007ffff5cae4f9 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) ()
    at /usr/lib/libQt5Core.so.5
#11 0x00007ffff5d049f4 in  () at /usr/lib/libQt5Core.so.5
#12 0x00007ffff57434dc in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
#13 0x00007ffff5797799 in  () at /usr/lib/libglib-2.0.so.0
#14 0x00007ffff5740bc1 in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#15 0x00007ffff5d04026 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
    at /usr/lib/libQt5Core.so.5
#16 0x00007ffff5ca9d6c in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) ()
    at /usr/lib/libQt5Core.so.5
--Type <RET> for more, q to quit, c to continue without paging--c
#17 0x00007ffff5cb22d4 in QCoreApplication::exec() () at /usr/lib/libQt5Core.so.5
#18 0x00005555558594c3 in main ()
```

**Comment by exaCORE42** [comment]
seems to be fixed with most recent commit
