### ISSUE TITLE
Crash when attempting to join a space via matrix URI

### ISSUE THREAD

**Issue by tastytea** [Nheko-Reborn/nheko#825]
### Describe the bug

When I try to join the space `#fedibikes-de:tchncs.de` via `matrix:` URI, nheko reproducibly crashes. When I already am in the space, it does not crash.

### To Reproduce

1. Open `matrix:r/fedibikes-de%3Atchncs.de?action=join&via=tchncs.de` in nheko
2. Click yes
3. Observe crash 🙁

### Version

0.9.0

### Operating system

Linux

### Installation method

Some repository (AUR, homebrew, distribution repository, PPA, etc)

### Qt version

5.15.2

### C++ compiler

GCC 11.2.0

### Desktop Environment

i3

### Did you use profiles?

- [ ] Profiles used?

### Relevant log output

```shell
[2021-11-23 22:59:44.916] [ui] [debug] begin insert from 146 to 172
[2021-11-23 22:59:44.916] [ui] [debug] data changed 145 to 145
[2021-11-23 22:59:58.611] [ui] [info] Received uri! matrix:r/fedibikes-de%3Atchncs.de?action=join&via=tchncs.de
[2021-11-23 22:59:58.611] [ui] [info] item: action=join
[2021-11-23 22:59:58.611] [ui] [info] item: via=tchncs.de
```

### Backtrace

```shell
warning: Can't open file /memfd:/.glXXXXXX (deleted) during file-backed mapping note processing

warning: Can't open file /memfd:xorg (deleted) during file-backed mapping note processing

warning: Can't open file /memfd:JITCode:QtQml (deleted) during file-backed mapping note processing

warning: Can't open file /memfd:unknown-usage:QtQml (deleted) during file-backed mapping note processing

warning: Can't open file /SYSV00000000 (deleted) during file-backed mapping note processing

warning: Can't open file /memfd:/.nvidia_drv.XXXXXX (deleted) during file-backed mapping note processing

warning: Can't open file /memfd:pulseaudio (deleted) during file-backed mapping note processing

warning: Can't open file /memfd:JSGCHeap:QtQml (deleted) during file-backed mapping note processing

warning: Can't open file /memfd:JSVMStack:QtQml (deleted) during file-backed mapping note processing

warning: Can't open file /SYSV5103005d (deleted) during file-backed mapping note processing
[New LWP 8821]
[New LWP 8830]
[New LWP 8823]
[New LWP 8824]
[New LWP 8854]
[New LWP 8841]
[New LWP 8847]
[New LWP 8850]
[New LWP 8853]
[New LWP 11449]
[New LWP 11450]
[New LWP 8831]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `nheko'.
Program terminated with signal SIGABRT, Aborted.
#0  0x00007fca6217506e in raise () from /lib64/libpthread.so.0
[Current thread is 1 (Thread 0x7fca64678f40 (LWP 8821))]

Thread 12 (Thread 0x7fca57fff640 (LWP 8831)):
#0  0x00007fca6209069f in poll () at /lib64/libc.so.6
#1  0x00007fca6258d75e in g_main_context_poll () at ../glib-2.68.4/glib/gmain.c:4434
#2  g_main_context_iterate () at ../glib-2.68.4/glib/gmain.c:4126
#3  0x00007fca6258da83 in g_main_loop_run () at ../glib-2.68.4/glib/gmain.c:4329
#4  0x00007fca611bfd96 in gdbus_shared_thread_func () at ../glib-2.68.4/gio/gdbusprivate.c:280
#5  0x00007fca625b60dd in g_thread_proxy () at ../glib-2.68.4/glib/gthread.c:826
#6  0x00007fca6216ad4e in start_thread () at /lib64/libpthread.so.0
#7  0x00007fca6209afaf in clone () at /lib64/libc.so.6

Thread 11 (Thread 0x7fca37efe640 (LWP 11450)):
#0  0x00007fca62092d51 in select () at /lib64/libc.so.6
#1  0x00007fca1ad22101 in  () at /usr/lib64/libnvidia-glcore.so.470.82.00
#2  0x00007fca1ad1fc2d in  () at /usr/lib64/libnvidia-glcore.so.470.82.00
#3  0x00007fca6216ad4e in start_thread () at /lib64/libpthread.so.0
#4  0x00007fca6209afaf in clone () at /lib64/libc.so.6

Thread 10 (Thread 0x7fca556d0640 (LWP 11449)):
#0  0x00007fca621770aa in __futex_abstimed_wait_common64 () at /lib64/libpthread.so.0
#1  0x00007fca62170ca0 in pthread_cond_wait@@GLIBC_2.3.2 () at /lib64/libpthread.so.0
#2  0x00007fca62912fd3 in QWaitConditionPrivate::wait(QDeadlineTimer) () at /var/tmp/portage/dev-qt/qtcore-5.15.2-r10/work/qtbase-a4f9e56975fa6ab4a1f63a9b34a4d77b1cfe4acd/src/corelib/thread/qwaitcondition_unix.cpp:146
#3  QWaitCondition::wait(QMutex*, QDeadlineTimer) () at /var/tmp/portage/dev-qt/qtcore-5.15.2-r10/work/qtbase-a4f9e56975fa6ab4a1f63a9b34a4d77b1cfe4acd/src/corelib/thread/qwaitcondition_unix.cpp:225
#4  0x00007fca642cdf67 in QSGRenderThreadEventQueue::takeEvent(bool) () at /var/tmp/portage/dev-qt/qtdeclarative-5.15.2-r12/work/qtdeclarative-1c33a9d045897ce755a818ebff7ddecae97885d3/src/quick/scenegraph/qsgthreadedrenderloop.cpp:257
#5  QSGRenderThread::processEventsAndWaitForMore() () at /var/tmp/portage/dev-qt/qtdeclarative-5.15.2-r12/work/qtdeclarative-1c33a9d045897ce755a818ebff7ddecae97885d3/src/quick/scenegraph/qsgthreadedrenderloop.cpp:936
#6  0x00007fca642d02f9 in QSGRenderThread::run() () at /var/tmp/portage/dev-qt/qtdeclarative-5.15.2-r12/work/qtdeclarative-1c33a9d045897ce755a818ebff7ddecae97885d3/src/quick/scenegraph/qsgthreadedrenderloop.cpp:1053
#7  0x00007fca6290d910 in QThreadPrivate::start(void*) () at /var/tmp/portage/dev-qt/qtcore-5.15.2-r10/work/qtbase-a4f9e56975fa6ab4a1f63a9b34a4d77b1cfe4acd/src/corelib/thread/qthread_unix.cpp:329
#8  0x00007fca6216ad4e in start_thread () at /lib64/libpthread.so.0
#9  0x00007fca6209afaf in clone () at /lib64/libc.so.6

Thread 9 (Thread 0x7fca357c2640 (LWP 8853)):
#0  0x00007fca6209069f in poll () at /lib64/libc.so.6
#1  0x00007fca6258d75e in g_main_context_poll () at ../glib-2.68.4/glib/gmain.c:4434
#2  g_main_context_iterate () at ../glib-2.68.4/glib/gmain.c:4126
#3  0x00007fca6258d86f in g_main_context_iteration () at ../glib-2.68.4/glib/gmain.c:4196
#4  0x00007fca62b05340 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /var/tmp/portage/dev-qt/qtcore-5.15.2-r10/work/qtbase-a4f9e56975fa6ab4a1f63a9b34a4d77b1cfe4acd/src/corelib/kernel/qeventdispatcher_glib.cpp:423
#5  0x00007fca62ab3dc3 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /var/tmp/portage/dev-qt/qtcore-5.15.2-r10/work/qtbase-a4f9e56975fa6ab4a1f63a9b34a4d77b1cfe4acd/src/corelib/kernel/qeventloop.cpp:232
#6  0x00007fca6290c857 in QThread::exec() () at /var/tmp/portage/dev-qt/qtcore-5.15.2-r10/work/qtbase-a4f9e56975fa6ab4a1f63a9b34a4d77b1cfe4acd/src/corelib/thread/qthread.cpp:547
#7  0x00007fca63f6c9f5 in QQmlThreadPrivate::run() () at /var/tmp/portage/dev-qt/qtdeclarative-5.15.2-r12/work/qtdeclarative-1c33a9d045897ce755a818ebff7ddecae97885d3/src/qml/qml/ftw/qqmlthread.cpp:155
#8  0x00007fca6290d910 in QThreadPrivate::start(void*) () at /var/tmp/portage/dev-qt/qtcore-5.15.2-r10/work/qtbase-a4f9e56975fa6ab4a1f63a9b34a4d77b1cfe4acd/src/corelib/thread/qthread_unix.cpp:329
#9  0x00007fca6216ad4e in start_thread () at /lib64/libpthread.so.0
#10 0x00007fca6209afaf in clone () at /lib64/libc.so.6

Thread 8 (Thread 0x7fca36251640 (LWP 8850)):
#0  0x00007fca6209069f in poll () at /lib64/libc.so.6
#1  0x00007fca6258d75e in g_main_context_poll () at ../glib-2.68.4/glib/gmain.c:4434
#2  g_main_context_iterate () at ../glib-2.68.4/glib/gmain.c:4126
#3  0x00007fca6258da83 in g_main_loop_run () at ../glib-2.68.4/glib/gmain.c:4329
#4  0x00007fca36b9ad32 in provider_thread () at ../gst-plugins-good-1.18.4/sys/v4l2/gstv4l2deviceprovider.c:403
#5  0x00007fca625b60dd in g_thread_proxy () at ../glib-2.68.4/glib/gthread.c:826
#6  0x00007fca6216ad4e in start_thread () at /lib64/libpthread.so.0
#7  0x00007fca6209afaf in clone () at /lib64/libc.so.6

Thread 7 (Thread 0x7fca36a52640 (LWP 8847)):
#0  0x00007fca6209069f in poll () at /lib64/libc.so.6
#1  0x00007fca61ca28a5 in poll_func () at /usr/lib64/libpulse.so.0
#2  0x00007fca61c93336 in pa_mainloop_poll () at /usr/lib64/libpulse.so.0
#3  0x00007fca61c93968 in pa_mainloop_iterate () at /usr/lib64/libpulse.so.0
#4  0x00007fca61c93a02 in pa_mainloop_run () at /usr/lib64/libpulse.so.0
#5  0x00007fca61ca296d in thread () at /usr/lib64/libpulse.so.0
#6  0x00007fca60fe1b8e in internal_thread_func () at /usr/lib64/pulseaudio/libpulsecommon-15.0.so
#7  0x00007fca6216ad4e in start_thread () at /lib64/libpthread.so.0
#8  0x00007fca6209afaf in clone () at /lib64/libc.so.6

Thread 6 (Thread 0x7fca374fa640 (LWP 8841)):
#0  0x00007fca6209069f in poll () at /lib64/libc.so.6
#1  0x00007fca6258d75e in g_main_context_poll () at ../glib-2.68.4/glib/gmain.c:4434
#2  g_main_context_iterate () at ../glib-2.68.4/glib/gmain.c:4126
#3  0x00007fca6258d86f in g_main_context_iteration () at ../glib-2.68.4/glib/gmain.c:4196
#4  0x00007fca62b05340 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /var/tmp/portage/dev-qt/qtcore-5.15.2-r10/work/qtbase-a4f9e56975fa6ab4a1f63a9b34a4d77b1cfe4acd/src/corelib/kernel/qeventdispatcher_glib.cpp:423
#5  0x00007fca62ab3dc3 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /var/tmp/portage/dev-qt/qtcore-5.15.2-r10/work/qtbase-a4f9e56975fa6ab4a1f63a9b34a4d77b1cfe4acd/src/corelib/kernel/qeventloop.cpp:232
#6  0x00007fca6290c857 in QThread::exec() () at /var/tmp/portage/dev-qt/qtcore-5.15.2-r10/work/qtbase-a4f9e56975fa6ab4a1f63a9b34a4d77b1cfe4acd/src/corelib/thread/qthread.cpp:547
#7  0x00007fca63bda64f in QDBusConnectionManager::run() () at /var/tmp/portage/dev-qt/qtdbus-5.15.2-r10/work/qtbase-a4f9e56975fa6ab4a1f63a9b34a4d77b1cfe4acd/src/dbus/qdbusconnection.cpp:179
#8  0x00007fca6290d910 in QThreadPrivate::start(void*) () at /var/tmp/portage/dev-qt/qtcore-5.15.2-r10/work/qtbase-a4f9e56975fa6ab4a1f63a9b34a4d77b1cfe4acd/src/corelib/thread/qthread_unix.cpp:329
#9  0x00007fca6216ad4e in start_thread () at /lib64/libpthread.so.0
#10 0x00007fca6209afaf in clone () at /lib64/libc.so.6

Thread 5 (Thread 0x7fca566d2640 (LWP 8854)):
#0  0x00007fca6209069f in poll () at /lib64/libc.so.6
#1  0x00007fca6258d75e in g_main_context_poll () at ../glib-2.68.4/glib/gmain.c:4434
#2  g_main_context_iterate () at ../glib-2.68.4/glib/gmain.c:4126
#3  0x00007fca6258d86f in g_main_context_iteration () at ../glib-2.68.4/glib/gmain.c:4196
#4  0x00007fca62b05340 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /var/tmp/portage/dev-qt/qtcore-5.15.2-r10/work/qtbase-a4f9e56975fa6ab4a1f63a9b34a4d77b1cfe4acd/src/corelib/kernel/qeventdispatcher_glib.cpp:423
#5  0x00007fca62ab3dc3 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /var/tmp/portage/dev-qt/qtcore-5.15.2-r10/work/qtbase-a4f9e56975fa6ab4a1f63a9b34a4d77b1cfe4acd/src/corelib/kernel/qeventloop.cpp:232
#6  0x00007fca6290c857 in QThread::exec() () at /var/tmp/portage/dev-qt/qtcore-5.15.2-r10/work/qtbase-a4f9e56975fa6ab4a1f63a9b34a4d77b1cfe4acd/src/corelib/thread/qthread.cpp:547
#7  0x00007fca6421cfe6 in QQuickPixmapReader::run() () at /var/tmp/portage/dev-qt/qtdeclarative-5.15.2-r12/work/qtdeclarative-1c33a9d045897ce755a818ebff7ddecae97885d3/src/quick/util/qquickpixmapcache.cpp:1024
#8  0x00007fca6290d910 in QThreadPrivate::start(void*) () at /var/tmp/portage/dev-qt/qtcore-5.15.2-r10/work/qtbase-a4f9e56975fa6ab4a1f63a9b34a4d77b1cfe4acd/src/corelib/thread/qthread_unix.cpp:329
#9  0x00007fca6216ad4e in start_thread () at /lib64/libpthread.so.0
#10 0x00007fca6209afaf in clone () at /lib64/libc.so.6

Thread 4 (Thread 0x7fca5dad2640 (LWP 8824)):
#0  0x00007fca6209069f in poll () at /lib64/libc.so.6
#1  0x00007fca62507c90 in poll () at /usr/include/bits/poll2.h:47
#2  _xcb_conn_wait () at /var/tmp/portage/x11-libs/libxcb-1.14/work/libxcb-1.14/src/xcb_conn.c:480
#3  0x00007fca62509677 in xcb_wait_for_event () at /var/tmp/portage/x11-libs/libxcb-1.14/work/libxcb-1.14/src/xcb_in.c:697
#4  0x00007fca5dd07230 in QXcbEventQueue::run() () at /var/tmp/portage/dev-qt/qtgui-5.15.2-r13/work/qtbase-a4f9e56975fa6ab4a1f63a9b34a4d77b1cfe4acd/src/plugins/platforms/xcb/qxcbeventqueue.cpp:228
#5  0x00007fca6290d910 in QThreadPrivate::start(void*) () at /var/tmp/portage/dev-qt/qtcore-5.15.2-r10/work/qtbase-a4f9e56975fa6ab4a1f63a9b34a4d77b1cfe4acd/src/corelib/thread/qthread_unix.cpp:329
#6  0x00007fca6216ad4e in start_thread () at /lib64/libpthread.so.0
#7  0x00007fca6209afaf in clone () at /lib64/libc.so.6

Thread 3 (Thread 0x7fca5eb2a640 (LWP 8823)):
#0  0x00007fca6209b2d6 in epoll_wait () at /lib64/libc.so.6
#1  0x00007fca61c57f63 in epoll_dispatch () at /var/tmp/portage/dev-libs/libevent-2.1.12/work/libevent-2.1.12-stable/epoll.c:465
#2  0x00007fca61c4e0c9 in event_base_loop () at /var/tmp/portage/dev-libs/libevent-2.1.12/work/libevent-2.1.12-stable/event.c:1992
#3  0x00007fca623b8f54 in execute_native_thread_routine() () at /var/tmp/portage/sys-devel/gcc-11.2.0/work/gcc-11.2.0/libstdc++-v3/src/c++11/thread.cc:82
#4  0x00007fca6216ad4e in start_thread () at /lib64/libpthread.so.0
#5  0x00007fca6209afaf in clone () at /lib64/libc.so.6

Thread 2 (Thread 0x7fca577fe640 (LWP 8830)):
#0  0x00007fca6209069f in poll () at /lib64/libc.so.6
#1  0x00007fca6258d75e in g_main_context_poll () at ../glib-2.68.4/glib/gmain.c:4434
#2  g_main_context_iterate () at ../glib-2.68.4/glib/gmain.c:4126
#3  0x00007fca6258d86f in g_main_context_iteration () at ../glib-2.68.4/glib/gmain.c:4196
#4  0x00007fca6258d8b1 in glib_worker_main () at ../glib-2.68.4/glib/gmain.c:6089
#5  0x00007fca625b60dd in g_thread_proxy () at ../glib-2.68.4/glib/gthread.c:826
#6  0x00007fca6216ad4e in start_thread () at /lib64/libpthread.so.0
#7  0x00007fca6209afaf in clone () at /lib64/libc.so.6

Thread 1 (Thread 0x7fca64678f40 (LWP 8821)):
#0  0x00007fca6217506e in raise () at /lib64/libpthread.so.0
#1  0x0000556ae388d48e in stacktraceHandler(int) () at /var/tmp/portage/net-im/nheko-0.9.0-r1/work/nheko-0.9.0/src/main.cpp:84
#2  0x00007fca621751d0 in <signal handler called> () at /lib64/libpthread.so.0
#3  0x00007fca62a0d5c2 in QIODevice::putChar(char) () at /var/tmp/portage/dev-qt/qtcore-5.15.2-r10/work/qtbase-a4f9e56975fa6ab4a1f63a9b34a4d77b1cfe4acd/src/corelib/io/qiodevice.cpp:1793
#4  0x0000556ae38c0d27 in SingleApplicationPrivate::slotDataAvailable(QLocalSocket*, unsigned int) () at /var/tmp/portage/net-im/nheko-0.9.0-r1/work/nheko-0.9.0/third_party/SingleApplication-3.3.0/singleapplication_p.cpp:499
#5  0x00007fca62ae7496 in QtPrivate::QSlotObjectBase::call(QObject*, void**) () at ../../include/QtCore/../../../qtbase-a4f9e56975fa6ab4a1f63a9b34a4d77b1cfe4acd/src/corelib/kernel/qobjectdefs_impl.h:398
#6  doActivate<false>(QObject*, int, void**) () at /var/tmp/portage/dev-qt/qtcore-5.15.2-r10/work/qtbase-a4f9e56975fa6ab4a1f63a9b34a4d77b1cfe4acd/src/corelib/kernel/qobject.cpp:3886
#7  0x00007fca62ae74dc in doActivate<false>(QObject*, int, void**) () at /var/tmp/portage/dev-qt/qtcore-5.15.2-r10/work/qtbase-a4f9e56975fa6ab4a1f63a9b34a4d77b1cfe4acd/src/corelib/kernel/qobject.cpp:3898
#8  0x00007fca62e75f97 in QAbstractSocketPrivate::emitReadyRead(int) () at /var/tmp/portage/dev-qt/qtnetwork-5.15.2-r11/work/qtbase-a4f9e56975fa6ab4a1f63a9b34a4d77b1cfe4acd/src/network/socket/qabstractsocket.cpp:1323
#9  QAbstractSocketPrivate::canReadNotification() () at /var/tmp/portage/dev-qt/qtnetwork-5.15.2-r11/work/qtbase-a4f9e56975fa6ab4a1f63a9b34a4d77b1cfe4acd/src/network/socket/qabstractsocket.cpp:748
#10 0x00007fca62e886c1 in QReadNotifier::event(QEvent*) () at /var/tmp/portage/dev-qt/qtnetwork-5.15.2-r11/work/qtbase-a4f9e56975fa6ab4a1f63a9b34a4d77b1cfe4acd/src/network/socket/qnativesocketengine.cpp:1274
#11 0x00007fca6366e42f in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /var/tmp/portage/dev-qt/qtwidgets-5.15.2-r11/work/qtbase-a4f9e56975fa6ab4a1f63a9b34a4d77b1cfe4acd/src/widgets/kernel/qapplication.cpp:3632
#12 0x00007fca62ab5290 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /var/tmp/portage/dev-qt/qtcore-5.15.2-r10/work/qtbase-a4f9e56975fa6ab4a1f63a9b34a4d77b1cfe4acd/src/corelib/kernel/qcoreapplication.cpp:1064
#13 0x00007fca62b05cfe in socketNotifierSourceDispatch() () at /var/tmp/portage/dev-qt/qtcore-5.15.2-r10/work/qtbase-a4f9e56975fa6ab4a1f63a9b34a4d77b1cfe4acd/src/corelib/kernel/qeventdispatcher_glib.cpp:107
#14 0x00007fca6258d52a in g_main_dispatch () at ../glib-2.68.4/glib/gmain.c:3337
#15 g_main_context_dispatch () at ../glib-2.68.4/glib/gmain.c:4055
#16 0x00007fca6258d7c0 in g_main_context_iterate () at ../glib-2.68.4/glib/gmain.c:4131
#17 0x00007fca6258d86f in g_main_context_iteration () at ../glib-2.68.4/glib/gmain.c:4196
#18 0x00007fca62b05340 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /var/tmp/portage/dev-qt/qtcore-5.15.2-r10/work/qtbase-a4f9e56975fa6ab4a1f63a9b34a4d77b1cfe4acd/src/corelib/kernel/qeventdispatcher_glib.cpp:423
#19 0x00007fca62ab3dc3 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /var/tmp/portage/dev-qt/qtcore-5.15.2-r10/work/qtbase-a4f9e56975fa6ab4a1f63a9b34a4d77b1cfe4acd/src/corelib/kernel/qeventloop.cpp:232
#20 0x00007fca62abbf0d in QCoreApplication::exec() () at /var/tmp/portage/dev-qt/qtcore-5.15.2-r10/work/qtbase-a4f9e56975fa6ab4a1f63a9b34a4d77b1cfe4acd/src/corelib/kernel/qcoreapplication.cpp:1375
#21 0x0000556ae35ee79e in main() () at /var/tmp/portage/net-im/nheko-0.9.0-r1/work/nheko-0.9.0/src/main.cpp:305
```

**Comment by deepbluev7** [comment]
Probably https://github.com/itay-grudev/SingleApplication/issues/138
